


/*------------------------------------------------------------------------------
<auto-generated>
	This code was generated from a template.

	Manual changes to this file may cause unexpected behavior in your application.
	Manual changes to this file will be overwritten if the code is regenerated.
 </auto-generated>
------------------------------------------------------------------------------*/

IF EXISTS(SELECT * FROM [INFORMATION_SCHEMA].[ROUTINES] WHERE SPECIFIC_SCHEMA = 'API' AND SPECIFIC_NAME = 'ServiceRequest_Insert')
BEGIN
	DROP PROCEDURE [API].[ServiceRequest]
END
GO

CREATE PROCEDURE [API].[ServiceRequest_Insert]
	 @ObjectGuid uniqueidentifier
	,@CompanyReferenceId nvarchar(128)
	,@ServiceCatalogueId smallint
	,@HarvestProjectId bigint
	,@Title nvarchar(256)
	,@Body nvarchar(max)
	,@RequestedDate datetime
	,@RequestedBy uniqueidentifier
	,@CancelledDate datetime
	,@AssignedTo uniqueidentifier
	,@StatusId tinyint
	,@DueDate date
	,@StartTime time
	,@EndTime time
	,@Price decimal(18,2)
	,@ModifiedUser nvarchar(100)
AS

DECLARE @Now DATETIME
SET @Now = GETDATE()

INSERT INTO dbo.[ServiceRequest]
(
	 [ObjectGuid]
	,[CompanyReferenceId]
	,[ServiceCatalogueId]
	,[HarvestProjectId]
	,[Title]
	,[Body]
	,[RequestedDate]
	,[RequestedBy]
	,[CancelledDate]
	,[AssignedTo]
	,[StatusId]
	,[DueDate]
	,[StartTime]
	,[EndTime]
	,[Price]
	,[ModifiedUser]
)
VALUES 
(
	 @ObjectGuid
	,@CompanyReferenceId
	,@ServiceCatalogueId
	,@HarvestProjectId
	,@Title
	,@Body
	,@RequestedDate
	,@RequestedBy
	,@CancelledDate
	,@AssignedTo
	,@StatusId
	,@DueDate
	,@StartTime
	,@EndTime
	,@Price
	,@ModifiedUser
)

DECLARE @Id INT
SELECT @Id = SCOPE_IDENTITY()

SELECT * FROM API.ServiceRequest WHERE Id = @Id

GO

IF EXISTS(SELECT * FROM [INFORMATION_SCHEMA].[ROUTINES] WHERE SPECIFIC_SCHEMA = 'API' AND SPECIFIC_NAME = 'ServiceRequest_Update')
BEGIN
	DROP PROCEDURE [API].[ServiceRequest_Update]
END
GO

CREATE PROCEDURE [API].[ServiceRequest_Update]
	 @Id int
	,@ObjectGuid uniqueidentifier
	,@CompanyReferenceId nvarchar(128)
	,@ServiceCatalogueId smallint
	,@HarvestProjectId bigint
	,@Title nvarchar(256)
	,@Body nvarchar(max)
	,@RequestedDate datetime
	,@RequestedBy uniqueidentifier
	,@CancelledDate datetime
	,@AssignedTo uniqueidentifier
	,@StatusId tinyint
	,@DueDate date
	,@StartTime time
	,@EndTime time
	,@Price decimal(18,2)
	,@ModifiedUser nvarchar(100)
AS

DECLARE @Now DATETIME
SET @Now = GETDATE()

UPDATE dbo.[ServiceRequest]
SET
	 [ObjectGuid] = @ObjectGuid
	,[CompanyReferenceId] = @CompanyReferenceId
	,[ServiceCatalogueId] = @ServiceCatalogueId
	,[HarvestProjectId] = @HarvestProjectId
	,[Title] = @Title
	,[Body] = @Body
	,[RequestedDate] = @RequestedDate
	,[RequestedBy] = @RequestedBy
	,[CancelledDate] = @CancelledDate
	,[AssignedTo] = @AssignedTo
	,[StatusId] = @StatusId
	,[DueDate] = @DueDate
	,[StartTime] = @StartTime
	,[EndTime] = @EndTime
	,[Price] = @Price
	,[ModifiedDate] = @Now
	,[ModifiedUser] = @ModifiedUser
WHERE 
	Id = @Id

GO

IF EXISTS(SELECT * FROM [INFORMATION_SCHEMA].[ROUTINES] WHERE SPECIFIC_SCHEMA = 'API' AND SPECIFIC_NAME = 'ServiceRequest_Delete')
BEGIN
	DROP PROCEDURE [API].[ServiceRequest_Delete]
END
GO

CREATE PROCEDURE [API].[ServiceRequest_Delete]
	 @Id int
AS

DECLARE @Now DATETIME
SET @Now = GETDATE()

DELETE FROM dbo.[ServiceRequest]
WHERE 
	Id = @Id
