//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableDay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AvailableDay()
        {
            this.AvailableSlots = new HashSet<AvailableSlot>();
        }
    
        public short Id { get; set; }
        public string PhysicianId { get; set; }
        public System.DateTime Day { get; set; }
        public Nullable<short> CompanyId { get; set; }
        public Nullable<short> LocationId { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public string CompanyName { get; set; }
        public string LocationName { get; set; }
        public string LocationOwnerDisplayName { get; set; }
        public string LocationOwnerId { get; set; }
        public string PhysicianName { get; set; }
        public bool IsPrebook { get; set; }
        public Nullable<bool> CompanyIsParent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailableSlot> AvailableSlots { get; set; }
    }
}
