//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public string EntityId { get; set; }
        public System.Guid EntityGuid { get; set; }
        public string DisplayName { get; set; }
        public string EntityType { get; set; }
    }
}
