//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public int Id { get; set; }
        public string InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string Currency { get; set; }
        public string Terms { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public System.Guid ServiceProviderGuid { get; set; }
        public string ServiceProviderName { get; set; }
        public string ServiceProviderEntityType { get; set; }
        public string ServiceProviderLogoCssClass { get; set; }
        public string ServiceProviderEmail { get; set; }
        public string ServiceProviderPhoneNumber { get; set; }
        public string ServiceProviderAddress1 { get; set; }
        public string ServiceProviderAddress2 { get; set; }
        public string ServiceProviderCity { get; set; }
        public string ServiceProviderPostalCode { get; set; }
        public string ServiceProviderProvince { get; set; }
        public string ServiceProviderCountry { get; set; }
        public System.Guid CustomerGuid { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEntityType { get; set; }
        public string CustomerAddress1 { get; set; }
        public string CustomerAddress2 { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerPostalCode { get; set; }
        public string CustomerProvince { get; set; }
        public string CustomerCountry { get; set; }
        public string CustomerEmail { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> TaxRateHst { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> PaymentReceivedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public System.Guid ObjectGuid { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual BillableEntity ServiceProvider { get; set; }
        public virtual BillableEntity Customer { get; set; }
    }
}
