//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.CountryID = 124;
        }
    
        public int Id { get; set; }
        public System.Guid ObjectGuid { get; set; }
        public Nullable<System.Guid> OwnerGuid { get; set; }
        public string EntityDisplayName { get; set; }
        public string EntityType { get; set; }
        public byte AddressTypeID { get; set; }
        public string AddressTypeName { get; set; }
        public string Name { get; set; }
        public string Attention { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public short CountryID { get; set; }
        public Nullable<short> ProvinceID { get; set; }
        public Nullable<short> LocationId { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public string CountryName { get; set; }
        public string CountryCode { get; set; }
        public string ProvinceName { get; set; }
        public string ProvinceCode { get; set; }
        public string LocationName { get; set; }
        public string EntityId { get; set; }
        public string LocationShortName { get; set; }
    }
}
