//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationArea
    {
        public short LookupId { get; set; }
        public string LookupName { get; set; }
        public short ItemId { get; set; }
        public string ItemText { get; set; }
        public short ItemValue { get; set; }
    }
}
