//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OrvosiEntities : DbContext
    {
        public OrvosiEntities()
            : base("name=OrvosiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompanyAssessorPackage> CompanyAssessorPackages { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<PhysicianCompany> PhysicianCompanies { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<SpecialRequest> SpecialRequests { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceCategory> ServiceCategories { get; set; }
        public virtual DbSet<ServicePortfolio> ServicePortfolios { get; set; }
        public virtual DbSet<ServiceRequest> ServiceRequests { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LookupItem> LookupItems { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<PhysicianInsurance> PhysicianInsurances { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<PhysicianLicense> PhysicianLicenses { get; set; }
        public virtual DbSet<ServiceCatalogue> ServiceCatalogues { get; set; }
        public virtual DbSet<LocationArea> LocationAreas { get; set; }
        public virtual DbSet<PhysicianLocationArea> PhysicianLocationAreas { get; set; }
        public virtual DbSet<AvailableDay> AvailableDays { get; set; }
        public virtual DbSet<AvailableSlot> AvailableSlots { get; set; }
        public virtual DbSet<ServiceRequestTask> ServiceRequestTasks { get; set; }
        public virtual DbSet<ServiceRequestCostRollUp> ServiceRequestCostRollUps { get; set; }
        public virtual DbSet<Physician> Physicians { get; set; }
        public virtual DbSet<DashboardTaskSummary> DashboardTaskSummaries { get; set; }
    
        [DbFunction("OrvosiEntities", "fn_Weekdays")]
        public virtual IQueryable<fn_Weekdays_Result> fn_Weekdays(Nullable<System.DateTime> startDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_Weekdays_Result>("[OrvosiEntities].[fn_Weekdays](@StartDate)", startDateParameter);
        }
    
        [DbFunction("OrvosiEntities", "fn_Timeframe")]
        public virtual IQueryable<fn_Timeframe_Result> fn_Timeframe(string datePart, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var datePartParameter = datePart != null ?
                new ObjectParameter("DatePart", datePart) :
                new ObjectParameter("DatePart", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_Timeframe_Result>("[OrvosiEntities].[fn_Timeframe](@DatePart, @StartDate, @EndDate)", datePartParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<GetPhysicianGoogleAccount_Result> GetPhysicianGoogleAccount(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPhysicianGoogleAccount_Result>("GetPhysicianGoogleAccount", idParameter);
        }
    
        public virtual int SpecialRequest_Insert(string physicianId, Nullable<int> serviceId, string timeframe, string additionalNotes, string modifiedUserName, string modifiedUserId)
        {
            var physicianIdParameter = physicianId != null ?
                new ObjectParameter("PhysicianId", physicianId) :
                new ObjectParameter("PhysicianId", typeof(string));
    
            var serviceIdParameter = serviceId.HasValue ?
                new ObjectParameter("ServiceId", serviceId) :
                new ObjectParameter("ServiceId", typeof(int));
    
            var timeframeParameter = timeframe != null ?
                new ObjectParameter("Timeframe", timeframe) :
                new ObjectParameter("Timeframe", typeof(string));
    
            var additionalNotesParameter = additionalNotes != null ?
                new ObjectParameter("AdditionalNotes", additionalNotes) :
                new ObjectParameter("AdditionalNotes", typeof(string));
    
            var modifiedUserNameParameter = modifiedUserName != null ?
                new ObjectParameter("ModifiedUserName", modifiedUserName) :
                new ObjectParameter("ModifiedUserName", typeof(string));
    
            var modifiedUserIdParameter = modifiedUserId != null ?
                new ObjectParameter("ModifiedUserId", modifiedUserId) :
                new ObjectParameter("ModifiedUserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SpecialRequest_Insert", physicianIdParameter, serviceIdParameter, timeframeParameter, additionalNotesParameter, modifiedUserNameParameter, modifiedUserIdParameter);
        }
    
        public virtual int SpecialRequest_Update(Nullable<short> id, string physicianId, Nullable<int> serviceId, string timeframe, string additionalNotes, Nullable<System.DateTime> modifiedDate, string modifiedUserName, string modifiedUserId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(short));
    
            var physicianIdParameter = physicianId != null ?
                new ObjectParameter("PhysicianId", physicianId) :
                new ObjectParameter("PhysicianId", typeof(string));
    
            var serviceIdParameter = serviceId.HasValue ?
                new ObjectParameter("ServiceId", serviceId) :
                new ObjectParameter("ServiceId", typeof(int));
    
            var timeframeParameter = timeframe != null ?
                new ObjectParameter("Timeframe", timeframe) :
                new ObjectParameter("Timeframe", typeof(string));
    
            var additionalNotesParameter = additionalNotes != null ?
                new ObjectParameter("AdditionalNotes", additionalNotes) :
                new ObjectParameter("AdditionalNotes", typeof(string));
    
            var modifiedDateParameter = modifiedDate.HasValue ?
                new ObjectParameter("ModifiedDate", modifiedDate) :
                new ObjectParameter("ModifiedDate", typeof(System.DateTime));
    
            var modifiedUserNameParameter = modifiedUserName != null ?
                new ObjectParameter("ModifiedUserName", modifiedUserName) :
                new ObjectParameter("ModifiedUserName", typeof(string));
    
            var modifiedUserIdParameter = modifiedUserId != null ?
                new ObjectParameter("ModifiedUserId", modifiedUserId) :
                new ObjectParameter("ModifiedUserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SpecialRequest_Update", idParameter, physicianIdParameter, serviceIdParameter, timeframeParameter, additionalNotesParameter, modifiedDateParameter, modifiedUserNameParameter, modifiedUserIdParameter);
        }
    
        public virtual int AspNetUsers_Update(string id, string email, Nullable<bool> emailConfirmed, string phoneNumber, Nullable<bool> phoneNumberConfirmed, Nullable<bool> twoFactorEnabled, Nullable<System.DateTime> lockoutEndDateUtc, Nullable<bool> lockoutEnabled, Nullable<int> accessFailedCount, string userName, string title, string firstName, string lastName, string employeeId, Nullable<short> companyId, string companyName, string modifiedUser, Nullable<System.DateTime> lastActivationDate, Nullable<bool> isTestRecord)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var emailConfirmedParameter = emailConfirmed.HasValue ?
                new ObjectParameter("EmailConfirmed", emailConfirmed) :
                new ObjectParameter("EmailConfirmed", typeof(bool));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var phoneNumberConfirmedParameter = phoneNumberConfirmed.HasValue ?
                new ObjectParameter("PhoneNumberConfirmed", phoneNumberConfirmed) :
                new ObjectParameter("PhoneNumberConfirmed", typeof(bool));
    
            var twoFactorEnabledParameter = twoFactorEnabled.HasValue ?
                new ObjectParameter("TwoFactorEnabled", twoFactorEnabled) :
                new ObjectParameter("TwoFactorEnabled", typeof(bool));
    
            var lockoutEndDateUtcParameter = lockoutEndDateUtc.HasValue ?
                new ObjectParameter("LockoutEndDateUtc", lockoutEndDateUtc) :
                new ObjectParameter("LockoutEndDateUtc", typeof(System.DateTime));
    
            var lockoutEnabledParameter = lockoutEnabled.HasValue ?
                new ObjectParameter("LockoutEnabled", lockoutEnabled) :
                new ObjectParameter("LockoutEnabled", typeof(bool));
    
            var accessFailedCountParameter = accessFailedCount.HasValue ?
                new ObjectParameter("AccessFailedCount", accessFailedCount) :
                new ObjectParameter("AccessFailedCount", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(short));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("CompanyName", companyName) :
                new ObjectParameter("CompanyName", typeof(string));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            var lastActivationDateParameter = lastActivationDate.HasValue ?
                new ObjectParameter("LastActivationDate", lastActivationDate) :
                new ObjectParameter("LastActivationDate", typeof(System.DateTime));
    
            var isTestRecordParameter = isTestRecord.HasValue ?
                new ObjectParameter("IsTestRecord", isTestRecord) :
                new ObjectParameter("IsTestRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AspNetUsers_Update", idParameter, emailParameter, emailConfirmedParameter, phoneNumberParameter, phoneNumberConfirmedParameter, twoFactorEnabledParameter, lockoutEndDateUtcParameter, lockoutEnabledParameter, accessFailedCountParameter, userNameParameter, titleParameter, firstNameParameter, lastNameParameter, employeeIdParameter, companyIdParameter, companyNameParameter, modifiedUserParameter, lastActivationDateParameter, isTestRecordParameter);
        }
    
        public virtual int Account_Update(string id, string email, Nullable<bool> emailConfirmed, string phoneNumber, Nullable<bool> phoneNumberConfirmed, Nullable<bool> twoFactorEnabled, Nullable<System.DateTime> lockoutEndDateUtc, Nullable<bool> lockoutEnabled, Nullable<int> accessFailedCount, string userName, Nullable<short> companyId, string modifiedUser, Nullable<System.DateTime> lastActivationDate)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var emailConfirmedParameter = emailConfirmed.HasValue ?
                new ObjectParameter("EmailConfirmed", emailConfirmed) :
                new ObjectParameter("EmailConfirmed", typeof(bool));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var phoneNumberConfirmedParameter = phoneNumberConfirmed.HasValue ?
                new ObjectParameter("PhoneNumberConfirmed", phoneNumberConfirmed) :
                new ObjectParameter("PhoneNumberConfirmed", typeof(bool));
    
            var twoFactorEnabledParameter = twoFactorEnabled.HasValue ?
                new ObjectParameter("TwoFactorEnabled", twoFactorEnabled) :
                new ObjectParameter("TwoFactorEnabled", typeof(bool));
    
            var lockoutEndDateUtcParameter = lockoutEndDateUtc.HasValue ?
                new ObjectParameter("LockoutEndDateUtc", lockoutEndDateUtc) :
                new ObjectParameter("LockoutEndDateUtc", typeof(System.DateTime));
    
            var lockoutEnabledParameter = lockoutEnabled.HasValue ?
                new ObjectParameter("LockoutEnabled", lockoutEnabled) :
                new ObjectParameter("LockoutEnabled", typeof(bool));
    
            var accessFailedCountParameter = accessFailedCount.HasValue ?
                new ObjectParameter("AccessFailedCount", accessFailedCount) :
                new ObjectParameter("AccessFailedCount", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(short));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            var lastActivationDateParameter = lastActivationDate.HasValue ?
                new ObjectParameter("LastActivationDate", lastActivationDate) :
                new ObjectParameter("LastActivationDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Account_Update", idParameter, emailParameter, emailConfirmedParameter, phoneNumberParameter, phoneNumberConfirmedParameter, twoFactorEnabledParameter, lockoutEndDateUtcParameter, lockoutEnabledParameter, accessFailedCountParameter, userNameParameter, companyIdParameter, modifiedUserParameter, lastActivationDateParameter);
        }
    
        public virtual int Profile_Update(string id, string title, string firstName, string lastName, string employeeId, string modifiedUser, Nullable<bool> isTestRecord)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            var isTestRecordParameter = isTestRecord.HasValue ?
                new ObjectParameter("IsTestRecord", isTestRecord) :
                new ObjectParameter("IsTestRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Profile_Update", idParameter, titleParameter, firstNameParameter, lastNameParameter, employeeIdParameter, modifiedUserParameter, isTestRecordParameter);
        }
    
        public virtual int Service_Insert(string name, string description, string code, Nullable<decimal> price, Nullable<short> serviceCategoryId, Nullable<short> servicePortfolioId, string modifiedUser)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            var serviceCategoryIdParameter = serviceCategoryId.HasValue ?
                new ObjectParameter("ServiceCategoryId", serviceCategoryId) :
                new ObjectParameter("ServiceCategoryId", typeof(short));
    
            var servicePortfolioIdParameter = servicePortfolioId.HasValue ?
                new ObjectParameter("ServicePortfolioId", servicePortfolioId) :
                new ObjectParameter("ServicePortfolioId", typeof(short));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Service_Insert", nameParameter, descriptionParameter, codeParameter, priceParameter, serviceCategoryIdParameter, servicePortfolioIdParameter, modifiedUserParameter);
        }
    
        public virtual int Service_Update(Nullable<short> id, Nullable<System.Guid> objectGuid, string name, string description, string code, Nullable<decimal> price, Nullable<short> serviceCategoryId, Nullable<short> servicePortfolioId, string modifiedUser)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(short));
    
            var objectGuidParameter = objectGuid.HasValue ?
                new ObjectParameter("ObjectGuid", objectGuid) :
                new ObjectParameter("ObjectGuid", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            var serviceCategoryIdParameter = serviceCategoryId.HasValue ?
                new ObjectParameter("ServiceCategoryId", serviceCategoryId) :
                new ObjectParameter("ServiceCategoryId", typeof(short));
    
            var servicePortfolioIdParameter = servicePortfolioId.HasValue ?
                new ObjectParameter("ServicePortfolioId", servicePortfolioId) :
                new ObjectParameter("ServicePortfolioId", typeof(short));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Service_Update", idParameter, objectGuidParameter, nameParameter, descriptionParameter, codeParameter, priceParameter, serviceCategoryIdParameter, servicePortfolioIdParameter, modifiedUserParameter);
        }
    
        public virtual int Company_Insert(string name, string code, Nullable<bool> isParent, Nullable<int> parentId, string logoCssClass, string billingEmail, string reportsEmail, string phone, string modifiedUser)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var isParentParameter = isParent.HasValue ?
                new ObjectParameter("IsParent", isParent) :
                new ObjectParameter("IsParent", typeof(bool));
    
            var parentIdParameter = parentId.HasValue ?
                new ObjectParameter("ParentId", parentId) :
                new ObjectParameter("ParentId", typeof(int));
    
            var logoCssClassParameter = logoCssClass != null ?
                new ObjectParameter("LogoCssClass", logoCssClass) :
                new ObjectParameter("LogoCssClass", typeof(string));
    
            var billingEmailParameter = billingEmail != null ?
                new ObjectParameter("BillingEmail", billingEmail) :
                new ObjectParameter("BillingEmail", typeof(string));
    
            var reportsEmailParameter = reportsEmail != null ?
                new ObjectParameter("ReportsEmail", reportsEmail) :
                new ObjectParameter("ReportsEmail", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Company_Insert", nameParameter, codeParameter, isParentParameter, parentIdParameter, logoCssClassParameter, billingEmailParameter, reportsEmailParameter, phoneParameter, modifiedUserParameter);
        }
    
        public virtual int Company_Update(Nullable<short> id, Nullable<System.Guid> objectGuid, string name, string code, Nullable<bool> isParent, Nullable<int> parentId, string logoCssClass, string billingEmail, string reportsEmail, string phone, string modifiedUser)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(short));
    
            var objectGuidParameter = objectGuid.HasValue ?
                new ObjectParameter("ObjectGuid", objectGuid) :
                new ObjectParameter("ObjectGuid", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var isParentParameter = isParent.HasValue ?
                new ObjectParameter("IsParent", isParent) :
                new ObjectParameter("IsParent", typeof(bool));
    
            var parentIdParameter = parentId.HasValue ?
                new ObjectParameter("ParentId", parentId) :
                new ObjectParameter("ParentId", typeof(int));
    
            var logoCssClassParameter = logoCssClass != null ?
                new ObjectParameter("LogoCssClass", logoCssClass) :
                new ObjectParameter("LogoCssClass", typeof(string));
    
            var billingEmailParameter = billingEmail != null ?
                new ObjectParameter("BillingEmail", billingEmail) :
                new ObjectParameter("BillingEmail", typeof(string));
    
            var reportsEmailParameter = reportsEmail != null ?
                new ObjectParameter("ReportsEmail", reportsEmail) :
                new ObjectParameter("ReportsEmail", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Company_Update", idParameter, objectGuidParameter, nameParameter, codeParameter, isParentParameter, parentIdParameter, logoCssClassParameter, billingEmailParameter, reportsEmailParameter, phoneParameter, modifiedUserParameter);
        }
    
        public virtual int ServiceRequest_Delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ServiceRequest_Delete", idParameter);
        }
    
        public virtual int ServiceRequest_Insert(string companyReferenceId, string claimantName, Nullable<short> serviceCatalogueId, Nullable<int> addressId, Nullable<long> harvestProjectId, string title, string body, Nullable<System.DateTime> requestedDate, Nullable<System.Guid> requestedBy, Nullable<System.DateTime> cancelledDate, Nullable<System.Guid> caseCoordinatorId, Nullable<System.Guid> intakeAssistantId, Nullable<System.Guid> documentReviewerId, Nullable<short> availableSlotId, Nullable<System.DateTime> appointmentDate, Nullable<System.TimeSpan> startTime, Nullable<System.TimeSpan> endTime, Nullable<System.DateTime> dueDate, Nullable<decimal> price, string notes, string documentFolderLink, Nullable<short> companyId, Nullable<bool> isLateCancellation, Nullable<bool> isNoShow, Nullable<decimal> noShowRate, Nullable<decimal> lateCancellationRate, string modifiedUser)
        {
            var companyReferenceIdParameter = companyReferenceId != null ?
                new ObjectParameter("CompanyReferenceId", companyReferenceId) :
                new ObjectParameter("CompanyReferenceId", typeof(string));
    
            var claimantNameParameter = claimantName != null ?
                new ObjectParameter("ClaimantName", claimantName) :
                new ObjectParameter("ClaimantName", typeof(string));
    
            var serviceCatalogueIdParameter = serviceCatalogueId.HasValue ?
                new ObjectParameter("ServiceCatalogueId", serviceCatalogueId) :
                new ObjectParameter("ServiceCatalogueId", typeof(short));
    
            var addressIdParameter = addressId.HasValue ?
                new ObjectParameter("AddressId", addressId) :
                new ObjectParameter("AddressId", typeof(int));
    
            var harvestProjectIdParameter = harvestProjectId.HasValue ?
                new ObjectParameter("HarvestProjectId", harvestProjectId) :
                new ObjectParameter("HarvestProjectId", typeof(long));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var bodyParameter = body != null ?
                new ObjectParameter("Body", body) :
                new ObjectParameter("Body", typeof(string));
    
            var requestedDateParameter = requestedDate.HasValue ?
                new ObjectParameter("RequestedDate", requestedDate) :
                new ObjectParameter("RequestedDate", typeof(System.DateTime));
    
            var requestedByParameter = requestedBy.HasValue ?
                new ObjectParameter("RequestedBy", requestedBy) :
                new ObjectParameter("RequestedBy", typeof(System.Guid));
    
            var cancelledDateParameter = cancelledDate.HasValue ?
                new ObjectParameter("CancelledDate", cancelledDate) :
                new ObjectParameter("CancelledDate", typeof(System.DateTime));
    
            var caseCoordinatorIdParameter = caseCoordinatorId.HasValue ?
                new ObjectParameter("CaseCoordinatorId", caseCoordinatorId) :
                new ObjectParameter("CaseCoordinatorId", typeof(System.Guid));
    
            var intakeAssistantIdParameter = intakeAssistantId.HasValue ?
                new ObjectParameter("IntakeAssistantId", intakeAssistantId) :
                new ObjectParameter("IntakeAssistantId", typeof(System.Guid));
    
            var documentReviewerIdParameter = documentReviewerId.HasValue ?
                new ObjectParameter("DocumentReviewerId", documentReviewerId) :
                new ObjectParameter("DocumentReviewerId", typeof(System.Guid));
    
            var availableSlotIdParameter = availableSlotId.HasValue ?
                new ObjectParameter("AvailableSlotId", availableSlotId) :
                new ObjectParameter("AvailableSlotId", typeof(short));
    
            var appointmentDateParameter = appointmentDate.HasValue ?
                new ObjectParameter("AppointmentDate", appointmentDate) :
                new ObjectParameter("AppointmentDate", typeof(System.DateTime));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.TimeSpan));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.TimeSpan));
    
            var dueDateParameter = dueDate.HasValue ?
                new ObjectParameter("DueDate", dueDate) :
                new ObjectParameter("DueDate", typeof(System.DateTime));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            var notesParameter = notes != null ?
                new ObjectParameter("Notes", notes) :
                new ObjectParameter("Notes", typeof(string));
    
            var documentFolderLinkParameter = documentFolderLink != null ?
                new ObjectParameter("DocumentFolderLink", documentFolderLink) :
                new ObjectParameter("DocumentFolderLink", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(short));
    
            var isLateCancellationParameter = isLateCancellation.HasValue ?
                new ObjectParameter("IsLateCancellation", isLateCancellation) :
                new ObjectParameter("IsLateCancellation", typeof(bool));
    
            var isNoShowParameter = isNoShow.HasValue ?
                new ObjectParameter("IsNoShow", isNoShow) :
                new ObjectParameter("IsNoShow", typeof(bool));
    
            var noShowRateParameter = noShowRate.HasValue ?
                new ObjectParameter("NoShowRate", noShowRate) :
                new ObjectParameter("NoShowRate", typeof(decimal));
    
            var lateCancellationRateParameter = lateCancellationRate.HasValue ?
                new ObjectParameter("LateCancellationRate", lateCancellationRate) :
                new ObjectParameter("LateCancellationRate", typeof(decimal));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ServiceRequest_Insert", companyReferenceIdParameter, claimantNameParameter, serviceCatalogueIdParameter, addressIdParameter, harvestProjectIdParameter, titleParameter, bodyParameter, requestedDateParameter, requestedByParameter, cancelledDateParameter, caseCoordinatorIdParameter, intakeAssistantIdParameter, documentReviewerIdParameter, availableSlotIdParameter, appointmentDateParameter, startTimeParameter, endTimeParameter, dueDateParameter, priceParameter, notesParameter, documentFolderLinkParameter, companyIdParameter, isLateCancellationParameter, isNoShowParameter, noShowRateParameter, lateCancellationRateParameter, modifiedUserParameter);
        }
    
        public virtual int ServiceRequest_Update(Nullable<int> id, Nullable<System.Guid> objectGuid, string companyReferenceId, string claimantName, Nullable<short> serviceCatalogueId, Nullable<int> addressId, Nullable<long> harvestProjectId, string title, string body, Nullable<System.DateTime> requestedDate, Nullable<System.Guid> requestedBy, Nullable<System.DateTime> cancelledDate, Nullable<System.Guid> caseCoordinatorId, Nullable<System.Guid> intakeAssistantId, Nullable<System.Guid> documentReviewerId, Nullable<short> availableSlotId, Nullable<System.DateTime> appointmentDate, Nullable<System.TimeSpan> startTime, Nullable<System.TimeSpan> endTime, Nullable<System.DateTime> dueDate, Nullable<decimal> price, string notes, string documentFolderLink, Nullable<short> companyId, Nullable<bool> isLateCancellation, Nullable<bool> isNoShow, Nullable<decimal> noShowRate, Nullable<decimal> lateCancellationRate, string modifiedUser)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var objectGuidParameter = objectGuid.HasValue ?
                new ObjectParameter("ObjectGuid", objectGuid) :
                new ObjectParameter("ObjectGuid", typeof(System.Guid));
    
            var companyReferenceIdParameter = companyReferenceId != null ?
                new ObjectParameter("CompanyReferenceId", companyReferenceId) :
                new ObjectParameter("CompanyReferenceId", typeof(string));
    
            var claimantNameParameter = claimantName != null ?
                new ObjectParameter("ClaimantName", claimantName) :
                new ObjectParameter("ClaimantName", typeof(string));
    
            var serviceCatalogueIdParameter = serviceCatalogueId.HasValue ?
                new ObjectParameter("ServiceCatalogueId", serviceCatalogueId) :
                new ObjectParameter("ServiceCatalogueId", typeof(short));
    
            var addressIdParameter = addressId.HasValue ?
                new ObjectParameter("AddressId", addressId) :
                new ObjectParameter("AddressId", typeof(int));
    
            var harvestProjectIdParameter = harvestProjectId.HasValue ?
                new ObjectParameter("HarvestProjectId", harvestProjectId) :
                new ObjectParameter("HarvestProjectId", typeof(long));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var bodyParameter = body != null ?
                new ObjectParameter("Body", body) :
                new ObjectParameter("Body", typeof(string));
    
            var requestedDateParameter = requestedDate.HasValue ?
                new ObjectParameter("RequestedDate", requestedDate) :
                new ObjectParameter("RequestedDate", typeof(System.DateTime));
    
            var requestedByParameter = requestedBy.HasValue ?
                new ObjectParameter("RequestedBy", requestedBy) :
                new ObjectParameter("RequestedBy", typeof(System.Guid));
    
            var cancelledDateParameter = cancelledDate.HasValue ?
                new ObjectParameter("CancelledDate", cancelledDate) :
                new ObjectParameter("CancelledDate", typeof(System.DateTime));
    
            var caseCoordinatorIdParameter = caseCoordinatorId.HasValue ?
                new ObjectParameter("CaseCoordinatorId", caseCoordinatorId) :
                new ObjectParameter("CaseCoordinatorId", typeof(System.Guid));
    
            var intakeAssistantIdParameter = intakeAssistantId.HasValue ?
                new ObjectParameter("IntakeAssistantId", intakeAssistantId) :
                new ObjectParameter("IntakeAssistantId", typeof(System.Guid));
    
            var documentReviewerIdParameter = documentReviewerId.HasValue ?
                new ObjectParameter("DocumentReviewerId", documentReviewerId) :
                new ObjectParameter("DocumentReviewerId", typeof(System.Guid));
    
            var availableSlotIdParameter = availableSlotId.HasValue ?
                new ObjectParameter("AvailableSlotId", availableSlotId) :
                new ObjectParameter("AvailableSlotId", typeof(short));
    
            var appointmentDateParameter = appointmentDate.HasValue ?
                new ObjectParameter("AppointmentDate", appointmentDate) :
                new ObjectParameter("AppointmentDate", typeof(System.DateTime));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.TimeSpan));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.TimeSpan));
    
            var dueDateParameter = dueDate.HasValue ?
                new ObjectParameter("DueDate", dueDate) :
                new ObjectParameter("DueDate", typeof(System.DateTime));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            var notesParameter = notes != null ?
                new ObjectParameter("Notes", notes) :
                new ObjectParameter("Notes", typeof(string));
    
            var documentFolderLinkParameter = documentFolderLink != null ?
                new ObjectParameter("DocumentFolderLink", documentFolderLink) :
                new ObjectParameter("DocumentFolderLink", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(short));
    
            var isLateCancellationParameter = isLateCancellation.HasValue ?
                new ObjectParameter("IsLateCancellation", isLateCancellation) :
                new ObjectParameter("IsLateCancellation", typeof(bool));
    
            var isNoShowParameter = isNoShow.HasValue ?
                new ObjectParameter("IsNoShow", isNoShow) :
                new ObjectParameter("IsNoShow", typeof(bool));
    
            var noShowRateParameter = noShowRate.HasValue ?
                new ObjectParameter("NoShowRate", noShowRate) :
                new ObjectParameter("NoShowRate", typeof(decimal));
    
            var lateCancellationRateParameter = lateCancellationRate.HasValue ?
                new ObjectParameter("LateCancellationRate", lateCancellationRate) :
                new ObjectParameter("LateCancellationRate", typeof(decimal));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ServiceRequest_Update", idParameter, objectGuidParameter, companyReferenceIdParameter, claimantNameParameter, serviceCatalogueIdParameter, addressIdParameter, harvestProjectIdParameter, titleParameter, bodyParameter, requestedDateParameter, requestedByParameter, cancelledDateParameter, caseCoordinatorIdParameter, intakeAssistantIdParameter, documentReviewerIdParameter, availableSlotIdParameter, appointmentDateParameter, startTimeParameter, endTimeParameter, dueDateParameter, priceParameter, notesParameter, documentFolderLinkParameter, companyIdParameter, isLateCancellationParameter, isNoShowParameter, noShowRateParameter, lateCancellationRateParameter, modifiedUserParameter);
        }
    
        public virtual ObjectResult<Location_Select_PhysicianAndCompany_Result> Location_Select_PhysicianAndCompany(string physicianId, Nullable<short> companyId)
        {
            var physicianIdParameter = physicianId != null ?
                new ObjectParameter("PhysicianId", physicianId) :
                new ObjectParameter("PhysicianId", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Location_Select_PhysicianAndCompany_Result>("Location_Select_PhysicianAndCompany", physicianIdParameter, companyIdParameter);
        }
    
        public virtual int PhysicianInsurance_Delete(Nullable<short> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PhysicianInsurance_Delete", idParameter);
        }
    
        public virtual ObjectResult<PhysicianInsurance> PhysicianInsurance_Insert(string physicianId, string insurer, string policyNumber, Nullable<System.DateTime> expiryDate, Nullable<short> documentId, string modifiedUser)
        {
            var physicianIdParameter = physicianId != null ?
                new ObjectParameter("PhysicianId", physicianId) :
                new ObjectParameter("PhysicianId", typeof(string));
    
            var insurerParameter = insurer != null ?
                new ObjectParameter("Insurer", insurer) :
                new ObjectParameter("Insurer", typeof(string));
    
            var policyNumberParameter = policyNumber != null ?
                new ObjectParameter("PolicyNumber", policyNumber) :
                new ObjectParameter("PolicyNumber", typeof(string));
    
            var expiryDateParameter = expiryDate.HasValue ?
                new ObjectParameter("ExpiryDate", expiryDate) :
                new ObjectParameter("ExpiryDate", typeof(System.DateTime));
    
            var documentIdParameter = documentId.HasValue ?
                new ObjectParameter("DocumentId", documentId) :
                new ObjectParameter("DocumentId", typeof(short));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhysicianInsurance>("PhysicianInsurance_Insert", physicianIdParameter, insurerParameter, policyNumberParameter, expiryDateParameter, documentIdParameter, modifiedUserParameter);
        }
    
        public virtual ObjectResult<PhysicianInsurance> PhysicianInsurance_Insert(string physicianId, string insurer, string policyNumber, Nullable<System.DateTime> expiryDate, Nullable<short> documentId, string modifiedUser, MergeOption mergeOption)
        {
            var physicianIdParameter = physicianId != null ?
                new ObjectParameter("PhysicianId", physicianId) :
                new ObjectParameter("PhysicianId", typeof(string));
    
            var insurerParameter = insurer != null ?
                new ObjectParameter("Insurer", insurer) :
                new ObjectParameter("Insurer", typeof(string));
    
            var policyNumberParameter = policyNumber != null ?
                new ObjectParameter("PolicyNumber", policyNumber) :
                new ObjectParameter("PolicyNumber", typeof(string));
    
            var expiryDateParameter = expiryDate.HasValue ?
                new ObjectParameter("ExpiryDate", expiryDate) :
                new ObjectParameter("ExpiryDate", typeof(System.DateTime));
    
            var documentIdParameter = documentId.HasValue ?
                new ObjectParameter("DocumentId", documentId) :
                new ObjectParameter("DocumentId", typeof(short));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhysicianInsurance>("PhysicianInsurance_Insert", mergeOption, physicianIdParameter, insurerParameter, policyNumberParameter, expiryDateParameter, documentIdParameter, modifiedUserParameter);
        }
    
        public virtual int PhysicianInsurance_Update(Nullable<short> id, string physicianId, string insurer, string policyNumber, Nullable<System.DateTime> expiryDate, Nullable<short> documentId, string modifiedUser)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(short));
    
            var physicianIdParameter = physicianId != null ?
                new ObjectParameter("PhysicianId", physicianId) :
                new ObjectParameter("PhysicianId", typeof(string));
    
            var insurerParameter = insurer != null ?
                new ObjectParameter("Insurer", insurer) :
                new ObjectParameter("Insurer", typeof(string));
    
            var policyNumberParameter = policyNumber != null ?
                new ObjectParameter("PolicyNumber", policyNumber) :
                new ObjectParameter("PolicyNumber", typeof(string));
    
            var expiryDateParameter = expiryDate.HasValue ?
                new ObjectParameter("ExpiryDate", expiryDate) :
                new ObjectParameter("ExpiryDate", typeof(System.DateTime));
    
            var documentIdParameter = documentId.HasValue ?
                new ObjectParameter("DocumentId", documentId) :
                new ObjectParameter("DocumentId", typeof(short));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PhysicianInsurance_Update", idParameter, physicianIdParameter, insurerParameter, policyNumberParameter, expiryDateParameter, documentIdParameter, modifiedUserParameter);
        }
    
        public virtual int Document_Delete(Nullable<short> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Document_Delete", idParameter);
        }
    
        public virtual ObjectResult<Document> Document_Insert(Nullable<System.Guid> objectGuid, Nullable<System.Guid> ownedByObjectGuid, Nullable<short> documentTemplateId, Nullable<System.DateTime> effectiveDate, Nullable<System.DateTime> expiryDate, string path, string extension, string name, byte[] content, string contentType, string modifiedUser)
        {
            var objectGuidParameter = objectGuid.HasValue ?
                new ObjectParameter("ObjectGuid", objectGuid) :
                new ObjectParameter("ObjectGuid", typeof(System.Guid));
    
            var ownedByObjectGuidParameter = ownedByObjectGuid.HasValue ?
                new ObjectParameter("OwnedByObjectGuid", ownedByObjectGuid) :
                new ObjectParameter("OwnedByObjectGuid", typeof(System.Guid));
    
            var documentTemplateIdParameter = documentTemplateId.HasValue ?
                new ObjectParameter("DocumentTemplateId", documentTemplateId) :
                new ObjectParameter("DocumentTemplateId", typeof(short));
    
            var effectiveDateParameter = effectiveDate.HasValue ?
                new ObjectParameter("EffectiveDate", effectiveDate) :
                new ObjectParameter("EffectiveDate", typeof(System.DateTime));
    
            var expiryDateParameter = expiryDate.HasValue ?
                new ObjectParameter("ExpiryDate", expiryDate) :
                new ObjectParameter("ExpiryDate", typeof(System.DateTime));
    
            var pathParameter = path != null ?
                new ObjectParameter("Path", path) :
                new ObjectParameter("Path", typeof(string));
    
            var extensionParameter = extension != null ?
                new ObjectParameter("Extension", extension) :
                new ObjectParameter("Extension", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var contentParameter = content != null ?
                new ObjectParameter("Content", content) :
                new ObjectParameter("Content", typeof(byte[]));
    
            var contentTypeParameter = contentType != null ?
                new ObjectParameter("ContentType", contentType) :
                new ObjectParameter("ContentType", typeof(string));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Document>("Document_Insert", objectGuidParameter, ownedByObjectGuidParameter, documentTemplateIdParameter, effectiveDateParameter, expiryDateParameter, pathParameter, extensionParameter, nameParameter, contentParameter, contentTypeParameter, modifiedUserParameter);
        }
    
        public virtual ObjectResult<Document> Document_Insert(Nullable<System.Guid> objectGuid, Nullable<System.Guid> ownedByObjectGuid, Nullable<short> documentTemplateId, Nullable<System.DateTime> effectiveDate, Nullable<System.DateTime> expiryDate, string path, string extension, string name, byte[] content, string contentType, string modifiedUser, MergeOption mergeOption)
        {
            var objectGuidParameter = objectGuid.HasValue ?
                new ObjectParameter("ObjectGuid", objectGuid) :
                new ObjectParameter("ObjectGuid", typeof(System.Guid));
    
            var ownedByObjectGuidParameter = ownedByObjectGuid.HasValue ?
                new ObjectParameter("OwnedByObjectGuid", ownedByObjectGuid) :
                new ObjectParameter("OwnedByObjectGuid", typeof(System.Guid));
    
            var documentTemplateIdParameter = documentTemplateId.HasValue ?
                new ObjectParameter("DocumentTemplateId", documentTemplateId) :
                new ObjectParameter("DocumentTemplateId", typeof(short));
    
            var effectiveDateParameter = effectiveDate.HasValue ?
                new ObjectParameter("EffectiveDate", effectiveDate) :
                new ObjectParameter("EffectiveDate", typeof(System.DateTime));
    
            var expiryDateParameter = expiryDate.HasValue ?
                new ObjectParameter("ExpiryDate", expiryDate) :
                new ObjectParameter("ExpiryDate", typeof(System.DateTime));
    
            var pathParameter = path != null ?
                new ObjectParameter("Path", path) :
                new ObjectParameter("Path", typeof(string));
    
            var extensionParameter = extension != null ?
                new ObjectParameter("Extension", extension) :
                new ObjectParameter("Extension", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var contentParameter = content != null ?
                new ObjectParameter("Content", content) :
                new ObjectParameter("Content", typeof(byte[]));
    
            var contentTypeParameter = contentType != null ?
                new ObjectParameter("ContentType", contentType) :
                new ObjectParameter("ContentType", typeof(string));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Document>("Document_Insert", mergeOption, objectGuidParameter, ownedByObjectGuidParameter, documentTemplateIdParameter, effectiveDateParameter, expiryDateParameter, pathParameter, extensionParameter, nameParameter, contentParameter, contentTypeParameter, modifiedUserParameter);
        }
    
        public virtual int Document_Update(Nullable<short> id, Nullable<System.Guid> objectGuid, Nullable<System.Guid> ownedByObjectGuid, Nullable<short> documentTemplateId, Nullable<System.DateTime> effectiveDate, Nullable<System.DateTime> expiryDate, string path, string extension, string name, byte[] content, string contentType, string modifiedUser)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(short));
    
            var objectGuidParameter = objectGuid.HasValue ?
                new ObjectParameter("ObjectGuid", objectGuid) :
                new ObjectParameter("ObjectGuid", typeof(System.Guid));
    
            var ownedByObjectGuidParameter = ownedByObjectGuid.HasValue ?
                new ObjectParameter("OwnedByObjectGuid", ownedByObjectGuid) :
                new ObjectParameter("OwnedByObjectGuid", typeof(System.Guid));
    
            var documentTemplateIdParameter = documentTemplateId.HasValue ?
                new ObjectParameter("DocumentTemplateId", documentTemplateId) :
                new ObjectParameter("DocumentTemplateId", typeof(short));
    
            var effectiveDateParameter = effectiveDate.HasValue ?
                new ObjectParameter("EffectiveDate", effectiveDate) :
                new ObjectParameter("EffectiveDate", typeof(System.DateTime));
    
            var expiryDateParameter = expiryDate.HasValue ?
                new ObjectParameter("ExpiryDate", expiryDate) :
                new ObjectParameter("ExpiryDate", typeof(System.DateTime));
    
            var pathParameter = path != null ?
                new ObjectParameter("Path", path) :
                new ObjectParameter("Path", typeof(string));
    
            var extensionParameter = extension != null ?
                new ObjectParameter("Extension", extension) :
                new ObjectParameter("Extension", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var contentParameter = content != null ?
                new ObjectParameter("Content", content) :
                new ObjectParameter("Content", typeof(byte[]));
    
            var contentTypeParameter = contentType != null ?
                new ObjectParameter("ContentType", contentType) :
                new ObjectParameter("ContentType", typeof(string));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Document_Update", idParameter, objectGuidParameter, ownedByObjectGuidParameter, documentTemplateIdParameter, effectiveDateParameter, expiryDateParameter, pathParameter, extensionParameter, nameParameter, contentParameter, contentTypeParameter, modifiedUserParameter);
        }
    
        public virtual int PhysicianLicense_Delete(Nullable<short> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PhysicianLicense_Delete", idParameter);
        }
    
        public virtual ObjectResult<PhysicianLicense_Insert_Result> PhysicianLicense_Insert(string physicianId, string collegeName, string longName, Nullable<System.DateTime> expiryDate, string memberName, string certificateClass, Nullable<bool> isPrimary, Nullable<byte> preference, Nullable<short> documentId, Nullable<short> countryId, Nullable<short> provinceId, string modifiedUser)
        {
            var physicianIdParameter = physicianId != null ?
                new ObjectParameter("PhysicianId", physicianId) :
                new ObjectParameter("PhysicianId", typeof(string));
    
            var collegeNameParameter = collegeName != null ?
                new ObjectParameter("CollegeName", collegeName) :
                new ObjectParameter("CollegeName", typeof(string));
    
            var longNameParameter = longName != null ?
                new ObjectParameter("LongName", longName) :
                new ObjectParameter("LongName", typeof(string));
    
            var expiryDateParameter = expiryDate.HasValue ?
                new ObjectParameter("ExpiryDate", expiryDate) :
                new ObjectParameter("ExpiryDate", typeof(System.DateTime));
    
            var memberNameParameter = memberName != null ?
                new ObjectParameter("MemberName", memberName) :
                new ObjectParameter("MemberName", typeof(string));
    
            var certificateClassParameter = certificateClass != null ?
                new ObjectParameter("CertificateClass", certificateClass) :
                new ObjectParameter("CertificateClass", typeof(string));
    
            var isPrimaryParameter = isPrimary.HasValue ?
                new ObjectParameter("IsPrimary", isPrimary) :
                new ObjectParameter("IsPrimary", typeof(bool));
    
            var preferenceParameter = preference.HasValue ?
                new ObjectParameter("Preference", preference) :
                new ObjectParameter("Preference", typeof(byte));
    
            var documentIdParameter = documentId.HasValue ?
                new ObjectParameter("DocumentId", documentId) :
                new ObjectParameter("DocumentId", typeof(short));
    
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("CountryId", countryId) :
                new ObjectParameter("CountryId", typeof(short));
    
            var provinceIdParameter = provinceId.HasValue ?
                new ObjectParameter("ProvinceId", provinceId) :
                new ObjectParameter("ProvinceId", typeof(short));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhysicianLicense_Insert_Result>("PhysicianLicense_Insert", physicianIdParameter, collegeNameParameter, longNameParameter, expiryDateParameter, memberNameParameter, certificateClassParameter, isPrimaryParameter, preferenceParameter, documentIdParameter, countryIdParameter, provinceIdParameter, modifiedUserParameter);
        }
    
        public virtual int PhysicianLicense_Update(Nullable<short> id, string physicianId, string collegeName, string longName, Nullable<System.DateTime> expiryDate, string memberName, string certificateClass, Nullable<bool> isPrimary, Nullable<byte> preference, Nullable<short> documentId, Nullable<short> countryId, Nullable<short> provinceId, string modifiedUser)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(short));
    
            var physicianIdParameter = physicianId != null ?
                new ObjectParameter("PhysicianId", physicianId) :
                new ObjectParameter("PhysicianId", typeof(string));
    
            var collegeNameParameter = collegeName != null ?
                new ObjectParameter("CollegeName", collegeName) :
                new ObjectParameter("CollegeName", typeof(string));
    
            var longNameParameter = longName != null ?
                new ObjectParameter("LongName", longName) :
                new ObjectParameter("LongName", typeof(string));
    
            var expiryDateParameter = expiryDate.HasValue ?
                new ObjectParameter("ExpiryDate", expiryDate) :
                new ObjectParameter("ExpiryDate", typeof(System.DateTime));
    
            var memberNameParameter = memberName != null ?
                new ObjectParameter("MemberName", memberName) :
                new ObjectParameter("MemberName", typeof(string));
    
            var certificateClassParameter = certificateClass != null ?
                new ObjectParameter("CertificateClass", certificateClass) :
                new ObjectParameter("CertificateClass", typeof(string));
    
            var isPrimaryParameter = isPrimary.HasValue ?
                new ObjectParameter("IsPrimary", isPrimary) :
                new ObjectParameter("IsPrimary", typeof(bool));
    
            var preferenceParameter = preference.HasValue ?
                new ObjectParameter("Preference", preference) :
                new ObjectParameter("Preference", typeof(byte));
    
            var documentIdParameter = documentId.HasValue ?
                new ObjectParameter("DocumentId", documentId) :
                new ObjectParameter("DocumentId", typeof(short));
    
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("CountryId", countryId) :
                new ObjectParameter("CountryId", typeof(short));
    
            var provinceIdParameter = provinceId.HasValue ?
                new ObjectParameter("ProvinceId", provinceId) :
                new ObjectParameter("ProvinceId", typeof(short));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PhysicianLicense_Update", idParameter, physicianIdParameter, collegeNameParameter, longNameParameter, expiryDateParameter, memberNameParameter, certificateClassParameter, isPrimaryParameter, preferenceParameter, documentIdParameter, countryIdParameter, provinceIdParameter, modifiedUserParameter);
        }
    
        public virtual ObjectResult<GetServiceCatalogueMatrix_Result> GetServiceCatalogueMatrix(string physicianId, Nullable<short> companyId)
        {
            var physicianIdParameter = physicianId != null ?
                new ObjectParameter("PhysicianId", physicianId) :
                new ObjectParameter("PhysicianId", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetServiceCatalogueMatrix_Result>("GetServiceCatalogueMatrix", physicianIdParameter, companyIdParameter);
        }
    
        public virtual ObjectResult<GetServiceCatalogue_Result> GetServiceCatalogue(string physicianId)
        {
            var physicianIdParameter = physicianId != null ?
                new ObjectParameter("PhysicianId", physicianId) :
                new ObjectParameter("PhysicianId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetServiceCatalogue_Result>("GetServiceCatalogue", physicianIdParameter);
        }
    
        public virtual int Location_Delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Location_Delete", idParameter);
        }
    
        public virtual ObjectResult<Location_Insert_Result> Location_Insert(Nullable<System.Guid> ownerGuid, Nullable<byte> addressTypeID, string name, string attention, string address1, string address2, string city, string postalCode, Nullable<short> countryID, Nullable<short> provinceID, Nullable<short> locationId, string modifiedUser)
        {
            var ownerGuidParameter = ownerGuid.HasValue ?
                new ObjectParameter("OwnerGuid", ownerGuid) :
                new ObjectParameter("OwnerGuid", typeof(System.Guid));
    
            var addressTypeIDParameter = addressTypeID.HasValue ?
                new ObjectParameter("AddressTypeID", addressTypeID) :
                new ObjectParameter("AddressTypeID", typeof(byte));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var attentionParameter = attention != null ?
                new ObjectParameter("Attention", attention) :
                new ObjectParameter("Attention", typeof(string));
    
            var address1Parameter = address1 != null ?
                new ObjectParameter("Address1", address1) :
                new ObjectParameter("Address1", typeof(string));
    
            var address2Parameter = address2 != null ?
                new ObjectParameter("Address2", address2) :
                new ObjectParameter("Address2", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var postalCodeParameter = postalCode != null ?
                new ObjectParameter("PostalCode", postalCode) :
                new ObjectParameter("PostalCode", typeof(string));
    
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(short));
    
            var provinceIDParameter = provinceID.HasValue ?
                new ObjectParameter("ProvinceID", provinceID) :
                new ObjectParameter("ProvinceID", typeof(short));
    
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("LocationId", locationId) :
                new ObjectParameter("LocationId", typeof(short));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Location_Insert_Result>("Location_Insert", ownerGuidParameter, addressTypeIDParameter, nameParameter, attentionParameter, address1Parameter, address2Parameter, cityParameter, postalCodeParameter, countryIDParameter, provinceIDParameter, locationIdParameter, modifiedUserParameter);
        }
    
        public virtual int Location_Update(Nullable<int> id, Nullable<System.Guid> ownerGuid, Nullable<byte> addressTypeID, string name, string attention, string address1, string address2, string city, string postalCode, Nullable<short> countryID, Nullable<short> provinceID, Nullable<short> locationId, string modifiedUser)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var ownerGuidParameter = ownerGuid.HasValue ?
                new ObjectParameter("OwnerGuid", ownerGuid) :
                new ObjectParameter("OwnerGuid", typeof(System.Guid));
    
            var addressTypeIDParameter = addressTypeID.HasValue ?
                new ObjectParameter("AddressTypeID", addressTypeID) :
                new ObjectParameter("AddressTypeID", typeof(byte));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var attentionParameter = attention != null ?
                new ObjectParameter("Attention", attention) :
                new ObjectParameter("Attention", typeof(string));
    
            var address1Parameter = address1 != null ?
                new ObjectParameter("Address1", address1) :
                new ObjectParameter("Address1", typeof(string));
    
            var address2Parameter = address2 != null ?
                new ObjectParameter("Address2", address2) :
                new ObjectParameter("Address2", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var postalCodeParameter = postalCode != null ?
                new ObjectParameter("PostalCode", postalCode) :
                new ObjectParameter("PostalCode", typeof(string));
    
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(short));
    
            var provinceIDParameter = provinceID.HasValue ?
                new ObjectParameter("ProvinceID", provinceID) :
                new ObjectParameter("ProvinceID", typeof(short));
    
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("LocationId", locationId) :
                new ObjectParameter("LocationId", typeof(short));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Location_Update", idParameter, ownerGuidParameter, addressTypeIDParameter, nameParameter, attentionParameter, address1Parameter, address2Parameter, cityParameter, postalCodeParameter, countryIDParameter, provinceIDParameter, locationIdParameter, modifiedUserParameter);
        }
    
        public virtual ObjectResult<GetServiceCatalogue_Result> GetServiceCatalogueForCompany(string physicianId, Nullable<short> companyId)
        {
            var physicianIdParameter = physicianId != null ?
                new ObjectParameter("PhysicianId", physicianId) :
                new ObjectParameter("PhysicianId", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetServiceCatalogue_Result>("GetServiceCatalogueForCompany", physicianIdParameter, companyIdParameter);
        }
    
        public virtual int ServiceRequestTask_Delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ServiceRequestTask_Delete", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ServiceRequestTask_Insert(Nullable<int> serviceRequestId, string taskName, string guidance, string responsibleRoleId, string responsibleRoleName, Nullable<short> sequence, string assignedTo, Nullable<bool> isBillable, Nullable<decimal> hourlyRate, Nullable<decimal> estimatedHours, Nullable<decimal> actualHours, Nullable<System.DateTime> completedDate, string notes, Nullable<short> invoiceItemId, string modifiedUser)
        {
            var serviceRequestIdParameter = serviceRequestId.HasValue ?
                new ObjectParameter("ServiceRequestId", serviceRequestId) :
                new ObjectParameter("ServiceRequestId", typeof(int));
    
            var taskNameParameter = taskName != null ?
                new ObjectParameter("TaskName", taskName) :
                new ObjectParameter("TaskName", typeof(string));
    
            var guidanceParameter = guidance != null ?
                new ObjectParameter("Guidance", guidance) :
                new ObjectParameter("Guidance", typeof(string));
    
            var responsibleRoleIdParameter = responsibleRoleId != null ?
                new ObjectParameter("ResponsibleRoleId", responsibleRoleId) :
                new ObjectParameter("ResponsibleRoleId", typeof(string));
    
            var responsibleRoleNameParameter = responsibleRoleName != null ?
                new ObjectParameter("ResponsibleRoleName", responsibleRoleName) :
                new ObjectParameter("ResponsibleRoleName", typeof(string));
    
            var sequenceParameter = sequence.HasValue ?
                new ObjectParameter("Sequence", sequence) :
                new ObjectParameter("Sequence", typeof(short));
    
            var assignedToParameter = assignedTo != null ?
                new ObjectParameter("AssignedTo", assignedTo) :
                new ObjectParameter("AssignedTo", typeof(string));
    
            var isBillableParameter = isBillable.HasValue ?
                new ObjectParameter("IsBillable", isBillable) :
                new ObjectParameter("IsBillable", typeof(bool));
    
            var hourlyRateParameter = hourlyRate.HasValue ?
                new ObjectParameter("HourlyRate", hourlyRate) :
                new ObjectParameter("HourlyRate", typeof(decimal));
    
            var estimatedHoursParameter = estimatedHours.HasValue ?
                new ObjectParameter("EstimatedHours", estimatedHours) :
                new ObjectParameter("EstimatedHours", typeof(decimal));
    
            var actualHoursParameter = actualHours.HasValue ?
                new ObjectParameter("ActualHours", actualHours) :
                new ObjectParameter("ActualHours", typeof(decimal));
    
            var completedDateParameter = completedDate.HasValue ?
                new ObjectParameter("CompletedDate", completedDate) :
                new ObjectParameter("CompletedDate", typeof(System.DateTime));
    
            var notesParameter = notes != null ?
                new ObjectParameter("Notes", notes) :
                new ObjectParameter("Notes", typeof(string));
    
            var invoiceItemIdParameter = invoiceItemId.HasValue ?
                new ObjectParameter("InvoiceItemId", invoiceItemId) :
                new ObjectParameter("InvoiceItemId", typeof(short));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ServiceRequestTask_Insert", serviceRequestIdParameter, taskNameParameter, guidanceParameter, responsibleRoleIdParameter, responsibleRoleNameParameter, sequenceParameter, assignedToParameter, isBillableParameter, hourlyRateParameter, estimatedHoursParameter, actualHoursParameter, completedDateParameter, notesParameter, invoiceItemIdParameter, modifiedUserParameter);
        }
    
        public virtual int ServiceRequestTask_Update(Nullable<int> id, Nullable<int> serviceRequestId, string taskName, string guidance, string responsibleRoleId, string responsibleRoleName, Nullable<short> sequence, string assignedTo, Nullable<bool> isBillable, Nullable<decimal> hourlyRate, Nullable<decimal> estimatedHours, Nullable<decimal> actualHours, Nullable<System.DateTime> completedDate, string notes, Nullable<short> invoiceItemId, string modifiedUser)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var serviceRequestIdParameter = serviceRequestId.HasValue ?
                new ObjectParameter("ServiceRequestId", serviceRequestId) :
                new ObjectParameter("ServiceRequestId", typeof(int));
    
            var taskNameParameter = taskName != null ?
                new ObjectParameter("TaskName", taskName) :
                new ObjectParameter("TaskName", typeof(string));
    
            var guidanceParameter = guidance != null ?
                new ObjectParameter("Guidance", guidance) :
                new ObjectParameter("Guidance", typeof(string));
    
            var responsibleRoleIdParameter = responsibleRoleId != null ?
                new ObjectParameter("ResponsibleRoleId", responsibleRoleId) :
                new ObjectParameter("ResponsibleRoleId", typeof(string));
    
            var responsibleRoleNameParameter = responsibleRoleName != null ?
                new ObjectParameter("ResponsibleRoleName", responsibleRoleName) :
                new ObjectParameter("ResponsibleRoleName", typeof(string));
    
            var sequenceParameter = sequence.HasValue ?
                new ObjectParameter("Sequence", sequence) :
                new ObjectParameter("Sequence", typeof(short));
    
            var assignedToParameter = assignedTo != null ?
                new ObjectParameter("AssignedTo", assignedTo) :
                new ObjectParameter("AssignedTo", typeof(string));
    
            var isBillableParameter = isBillable.HasValue ?
                new ObjectParameter("IsBillable", isBillable) :
                new ObjectParameter("IsBillable", typeof(bool));
    
            var hourlyRateParameter = hourlyRate.HasValue ?
                new ObjectParameter("HourlyRate", hourlyRate) :
                new ObjectParameter("HourlyRate", typeof(decimal));
    
            var estimatedHoursParameter = estimatedHours.HasValue ?
                new ObjectParameter("EstimatedHours", estimatedHours) :
                new ObjectParameter("EstimatedHours", typeof(decimal));
    
            var actualHoursParameter = actualHours.HasValue ?
                new ObjectParameter("ActualHours", actualHours) :
                new ObjectParameter("ActualHours", typeof(decimal));
    
            var completedDateParameter = completedDate.HasValue ?
                new ObjectParameter("CompletedDate", completedDate) :
                new ObjectParameter("CompletedDate", typeof(System.DateTime));
    
            var notesParameter = notes != null ?
                new ObjectParameter("Notes", notes) :
                new ObjectParameter("Notes", typeof(string));
    
            var invoiceItemIdParameter = invoiceItemId.HasValue ?
                new ObjectParameter("InvoiceItemId", invoiceItemId) :
                new ObjectParameter("InvoiceItemId", typeof(short));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ServiceRequestTask_Update", idParameter, serviceRequestIdParameter, taskNameParameter, guidanceParameter, responsibleRoleIdParameter, responsibleRoleNameParameter, sequenceParameter, assignedToParameter, isBillableParameter, hourlyRateParameter, estimatedHoursParameter, actualHoursParameter, completedDateParameter, notesParameter, invoiceItemIdParameter, modifiedUserParameter);
        }
    
        public virtual ObjectResult<GetDashboardSchedule_Result> GetDashboardSchedule(Nullable<System.DateTime> now, string userId, Nullable<bool> isSuperAdmin)
        {
            var nowParameter = now.HasValue ?
                new ObjectParameter("Now", now) :
                new ObjectParameter("Now", typeof(System.DateTime));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var isSuperAdminParameter = isSuperAdmin.HasValue ?
                new ObjectParameter("IsSuperAdmin", isSuperAdmin) :
                new ObjectParameter("IsSuperAdmin", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDashboardSchedule_Result>("GetDashboardSchedule", nowParameter, userIdParameter, isSuperAdminParameter);
        }
    
        public virtual ObjectResult<GetDashboardServiceRequest_Result> GetDashboardServiceRequest(Nullable<System.DateTime> now)
        {
            var nowParameter = now.HasValue ?
                new ObjectParameter("Now", now) :
                new ObjectParameter("Now", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDashboardServiceRequest_Result>("GetDashboardServiceRequest", nowParameter);
        }
    
        public virtual int ServiceRequest_ToggleNoShow(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ServiceRequest_ToggleNoShow", idParameter);
        }
    
        public virtual int ServiceRequest_ToggleCancellation(Nullable<int> id, Nullable<System.DateTime> cancelledDate, Nullable<bool> isLateCancellation, string notes)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var cancelledDateParameter = cancelledDate.HasValue ?
                new ObjectParameter("CancelledDate", cancelledDate) :
                new ObjectParameter("CancelledDate", typeof(System.DateTime));
    
            var isLateCancellationParameter = isLateCancellation.HasValue ?
                new ObjectParameter("IsLateCancellation", isLateCancellation) :
                new ObjectParameter("IsLateCancellation", typeof(bool));
    
            var notesParameter = notes != null ?
                new ObjectParameter("Notes", notes) :
                new ObjectParameter("Notes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ServiceRequest_ToggleCancellation", idParameter, cancelledDateParameter, isLateCancellationParameter, notesParameter);
        }
    
        public virtual ObjectResult<Nullable<short>> AvailableDay_Insert(Nullable<System.DateTime> availableDay, string userId, Nullable<short> companyId, Nullable<short> locationId, Nullable<bool> isPrebook, string modifiedUser)
        {
            var availableDayParameter = availableDay.HasValue ?
                new ObjectParameter("AvailableDay", availableDay) :
                new ObjectParameter("AvailableDay", typeof(System.DateTime));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(short));
    
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("LocationId", locationId) :
                new ObjectParameter("LocationId", typeof(short));
    
            var isPrebookParameter = isPrebook.HasValue ?
                new ObjectParameter("IsPrebook", isPrebook) :
                new ObjectParameter("IsPrebook", typeof(bool));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<short>>("AvailableDay_Insert", availableDayParameter, userIdParameter, companyIdParameter, locationIdParameter, isPrebookParameter, modifiedUserParameter);
        }
    
        public virtual ObjectResult<Nullable<short>> AvailableSlot_Insert(Nullable<short> availableDayId, Nullable<System.TimeSpan> startTime, Nullable<System.TimeSpan> endTime, Nullable<short> duration, string modifiedUser)
        {
            var availableDayIdParameter = availableDayId.HasValue ?
                new ObjectParameter("AvailableDayId", availableDayId) :
                new ObjectParameter("AvailableDayId", typeof(short));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.TimeSpan));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.TimeSpan));
    
            var durationParameter = duration.HasValue ?
                new ObjectParameter("Duration", duration) :
                new ObjectParameter("Duration", typeof(short));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<short>>("AvailableSlot_Insert", availableDayIdParameter, startTimeParameter, endTimeParameter, durationParameter, modifiedUserParameter);
        }
    
        public virtual int AvailableDay_Delete(Nullable<short> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AvailableDay_Delete", idParameter);
        }
    
        public virtual int AvailableSlot_Delete(Nullable<short> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AvailableSlot_Delete", idParameter);
        }
    
        public virtual int ServiceCatalogue_Delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ServiceCatalogue_Delete", idParameter);
        }
    
        public virtual int ServiceCatalogue_Insert(string physicianId, Nullable<short> serviceId, Nullable<short> companyId, Nullable<short> locationId, Nullable<decimal> price, string modifiedUser, Nullable<decimal> noShowRate, Nullable<decimal> lateCancellationRate)
        {
            var physicianIdParameter = physicianId != null ?
                new ObjectParameter("PhysicianId", physicianId) :
                new ObjectParameter("PhysicianId", typeof(string));
    
            var serviceIdParameter = serviceId.HasValue ?
                new ObjectParameter("ServiceId", serviceId) :
                new ObjectParameter("ServiceId", typeof(short));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(short));
    
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("LocationId", locationId) :
                new ObjectParameter("LocationId", typeof(short));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            var noShowRateParameter = noShowRate.HasValue ?
                new ObjectParameter("NoShowRate", noShowRate) :
                new ObjectParameter("NoShowRate", typeof(decimal));
    
            var lateCancellationRateParameter = lateCancellationRate.HasValue ?
                new ObjectParameter("LateCancellationRate", lateCancellationRate) :
                new ObjectParameter("LateCancellationRate", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ServiceCatalogue_Insert", physicianIdParameter, serviceIdParameter, companyIdParameter, locationIdParameter, priceParameter, modifiedUserParameter, noShowRateParameter, lateCancellationRateParameter);
        }
    
        public virtual int ServiceCatalogue_Update(Nullable<int> id, string physicianId, Nullable<short> serviceId, Nullable<short> companyId, Nullable<short> locationId, Nullable<decimal> price, string modifiedUser, Nullable<decimal> noShowRate, Nullable<decimal> lateCancellationRate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var physicianIdParameter = physicianId != null ?
                new ObjectParameter("PhysicianId", physicianId) :
                new ObjectParameter("PhysicianId", typeof(string));
    
            var serviceIdParameter = serviceId.HasValue ?
                new ObjectParameter("ServiceId", serviceId) :
                new ObjectParameter("ServiceId", typeof(short));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(short));
    
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("LocationId", locationId) :
                new ObjectParameter("LocationId", typeof(short));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            var noShowRateParameter = noShowRate.HasValue ?
                new ObjectParameter("NoShowRate", noShowRate) :
                new ObjectParameter("NoShowRate", typeof(decimal));
    
            var lateCancellationRateParameter = lateCancellationRate.HasValue ?
                new ObjectParameter("LateCancellationRate", lateCancellationRate) :
                new ObjectParameter("LateCancellationRate", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ServiceCatalogue_Update", idParameter, physicianIdParameter, serviceIdParameter, companyIdParameter, locationIdParameter, priceParameter, modifiedUserParameter, noShowRateParameter, lateCancellationRateParameter);
        }
    }
}
