//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicianToCompanyServiceRequestInvoicePreview
    {
        public System.DateTime InvoiceDate { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Terms { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string CompanyGuid { get; set; }
        public string CompanyName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public System.Guid BillToGuid { get; set; }
        public string BillToName { get; set; }
        public string BillToAddress1 { get; set; }
        public string BillToAddress2 { get; set; }
        public string BillToAddress3 { get; set; }
        public string BillToEmail { get; set; }
        public string DescriptionLine1 { get; set; }
        public string DescriptionLine2 { get; set; }
        public string DescriptionLine3 { get; set; }
        public bool IsNoShow { get; set; }
        public decimal NoShowRate { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public bool IsLateCancellation { get; set; }
        public decimal LateCancellationRate { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public decimal TaxRateHst { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int ServiceRequestId { get; set; }
    }
}
