//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicianLicense
    {
        public short Id { get; set; }
        public string PhysicianId { get; set; }
        public string CollegeName { get; set; }
        public string LongName { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string MemberName { get; set; }
        public string CertificateClass { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<byte> Preference { get; set; }
        public Nullable<short> DocumentId { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
    }
}
