//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicianLocationArea
    {
        public short Id { get; set; }
        public System.Guid PhysicianId { get; set; }
        public short LocationId { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public string StatusText { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceIncrease { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public string LocationName { get; set; }
        public string PhysicianName { get; set; }
    }
}
