//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCatalogue
    {
        public short Id { get; set; }
        public Nullable<short> CompanyId { get; set; }
        public string PhysicianId { get; set; }
        public Nullable<short> ServiceId { get; set; }
        public Nullable<short> LocationId { get; set; }
        public Nullable<decimal> ServiceCataloguePriceOverride { get; set; }
        public string ServiceName { get; set; }
        public Nullable<decimal> ServicePrice { get; set; }
        public string PhysicianDisplayName { get; set; }
        public string CompanyName { get; set; }
        public string LocationName { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<decimal> NoShowRate { get; set; }
        public Nullable<decimal> LateCancellationRate { get; set; }
    }
}
