//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTask
    {
        public Nullable<short> ServiceCategoryId { get; set; }
        public string ServiceCategoryName { get; set; }
        public short Id { get; set; }
        public string TaskName { get; set; }
        public string Guidance { get; set; }
        public Nullable<decimal> EstimatedHours { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public Nullable<short> Sequence { get; set; }
        public Nullable<bool> IsBillable { get; set; }
        public string ResponsibleRoleId { get; set; }
        public string ResponsibleRoleName { get; set; }
        public Nullable<byte> TaskPhaseId { get; set; }
        public string TaskPhaseName { get; set; }
        public string DependsOn { get; set; }
        public Nullable<byte> DueDateBase { get; set; }
        public Nullable<short> DueDateDiff { get; set; }
        public string ShortName { get; set; }
        public bool IsCriticalPath { get; set; }
    }
}
