//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequestCostRollUp
    {
        public long Id { get; set; }
        public Nullable<int> ServiceRequestId { get; set; }
        public string DisplayName { get; set; }
        public string RoleName { get; set; }
        public string RoleCategoryName { get; set; }
        public string TaskName { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    }
}
