//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCatalogueRate
    {
        public int Id { get; set; }
        public Nullable<System.Guid> ServiceProviderGuid { get; set; }
        public Nullable<System.Guid> CustomerGuid { get; set; }
        public Nullable<decimal> NoShowRate { get; set; }
        public Nullable<decimal> LateCancellationRate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
    }
}
