//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public short Id { get; set; }
        public Nullable<System.Guid> ObjectGuid { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> DefaultPrice { get; set; }
        public Nullable<short> ServiceCategoryId { get; set; }
        public Nullable<short> ServicePortfolioId { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public string ServiceCategoryName { get; set; }
        public string ServicePortfolioName { get; set; }
    }
}
