//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialRequest
    {
        public short Id { get; set; }
        public Nullable<System.Guid> ObjectGuid { get; set; }
        public string PhysicianId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string Timeframe { get; set; }
        public string AdditionalNotes { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public string PhysicianDisplayName { get; set; }
        public string ServiceName { get; set; }
    }
}
