INSERT INTO [dbo].[PhysicianCompanyStatus] ([Id], [Name]) VALUES (1, N'Interested')
INSERT INTO [dbo].[PhysicianCompanyStatus] ([Id], [Name]) VALUES (2, N'Not interested')
INSERT INTO [dbo].[PhysicianCompanyStatus] ([Id], [Name]) VALUES (3, N'In progress')
INSERT INTO [dbo].[PhysicianCompanyStatus] ([Id], [Name]) VALUES (4, N'Active')
INSERT INTO [dbo].[PhysicianCompanyStatus] ([Id], [Name]) VALUES (5, N'Assessor Package Submitted')
INSERT INTO [dbo].[PhysicianCompanyStatus] ([Id], [Name]) VALUES (6, N'Ready to Work')
