INSERT INTO [dbo].[TaskStatus] ([Id], [Name], [DependentPrecedence], [ServiceRequestPrecedence]) VALUES (1, N'Waiting', 2, 3)
INSERT INTO [dbo].[TaskStatus] ([Id], [Name], [DependentPrecedence], [ServiceRequestPrecedence]) VALUES (2, N'ToDo', 3, 2)
INSERT INTO [dbo].[TaskStatus] ([Id], [Name], [DependentPrecedence], [ServiceRequestPrecedence]) VALUES (3, N'Done', 4, 5)
INSERT INTO [dbo].[TaskStatus] ([Id], [Name], [DependentPrecedence], [ServiceRequestPrecedence]) VALUES (4, N'Obsolete', 5, 4)
INSERT INTO [dbo].[TaskStatus] ([Id], [Name], [DependentPrecedence], [ServiceRequestPrecedence]) VALUES (5, N'OnHold', 1, 1)