// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    public partial class Address
    {
        public System.Guid Id { get; set; }
        public System.Guid? PhysicianId { get; set; }
        public System.Guid? CompanyId { get; set; }
        public byte AddressTypeId { get; set; }
        public string Name { get; set; }
        public string Attention { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public System.Guid CityId { get; set; }
        public string PostalCode { get; set; }
        public short TimeZoneId { get; set; }
        public bool IsBillingAddress { get; set; }

        public virtual System.Collections.Generic.ICollection<AvailableDay> AvailableDays { get; set; }
        public virtual System.Collections.Generic.ICollection<ServiceRequest> ServiceRequests { get; set; }


        public virtual AddressType AddressType { get; set; }

        public virtual City City { get; set; }

        public virtual Company Company { get; set; }

        public virtual Physician Physician { get; set; }

        public virtual TimeZone TimeZone { get; set; }

        public Address()
        {
            IsBillingAddress = false;
            AvailableDays = new System.Collections.Generic.List<AvailableDay>();
            ServiceRequests = new System.Collections.Generic.List<ServiceRequest>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
