// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    public partial class AvailableDay
    {
        public System.Guid Id { get; set; }
        public System.Guid PhysicianId { get; set; }
        public System.DateTime Day { get; set; }
        public System.Guid? CompanyId { get; set; }
        public System.Guid? AddressId { get; set; }
        public System.Guid? CityId { get; set; }

        public virtual System.Collections.Generic.ICollection<AvailableDayResource> AvailableDayResources { get; set; }
        public virtual System.Collections.Generic.ICollection<AvailableSlot> AvailableSlots { get; set; }


        public virtual Address Address { get; set; }

        public virtual City City { get; set; }

        public virtual Company Company { get; set; }

        public virtual Physician Physician { get; set; }

        public AvailableDay()
        {
            AvailableDayResources = new System.Collections.Generic.List<AvailableDayResource>();
            AvailableSlots = new System.Collections.Generic.List<AvailableSlot>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
