// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    public partial class AvailableSlot
    {
        public System.Guid Id { get; set; }
        public System.Guid AvailableDayId { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan? EndTime { get; set; }
        public short? Duration { get; set; }

        public virtual System.Collections.Generic.ICollection<ServiceRequest> ServiceRequests { get; set; }


        public virtual AvailableDay AvailableDay { get; set; }

        public AvailableSlot()
        {
            ServiceRequests = new System.Collections.Generic.List<ServiceRequest>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
