// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    public partial class AvailableDayResource
    {
        public System.Guid Id { get; set; }
        public System.Guid AvailableDayId { get; set; }
        public System.Guid UserId { get; set; }


        public virtual AvailableDay AvailableDay { get; set; }

        public virtual User User { get; set; }

        public AvailableDayResource()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
