// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    public partial class Case
    {
        public System.Guid Id { get; set; }
        public System.Guid PhysicianId { get; set; }
        public string CaseNumber { get; set; }
        public string AlternateKey { get; set; }
        public string ClaimantName { get; set; }
        public byte StatusId { get; set; }
        public System.Guid? StatusChangedById { get; set; }
        public System.DateTime? StatusChangedDate { get; set; }
        public string FolderUrl { get; set; }
        public byte? MedicolegalTypeId { get; set; }
        public string ReferralSource { get; set; }


        public virtual CaseStatu CaseStatu { get; set; }

        public virtual MedicolegalType MedicolegalType { get; set; }

        public virtual Physician Physician { get; set; }

        public Case()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
