// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    public partial class Company
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public string ColorCode { get; set; }
        public System.Guid? PhysicianId { get; set; }
        public string BillingEmail { get; set; }
        public string ReportsEmail { get; set; }
        public string PhoneNumber { get; set; }
        public System.Guid? ParentId { get; set; }
        public int NoShowRate { get; set; }
        public int LateCancellationRate { get; set; }
        public int LateCancellationPolicy { get; set; }
        public byte LateCancellationRateFormat { get; set; }
        public byte NoShowRateFormat { get; set; }

        public virtual System.Collections.Generic.ICollection<Address> Addresses { get; set; }
        public virtual System.Collections.Generic.ICollection<AvailableDay> AvailableDays { get; set; }
        public virtual System.Collections.Generic.ICollection<Company> Companies { get; set; }
        public virtual System.Collections.Generic.ICollection<Service> Services { get; set; }


        public virtual Company Parent { get; set; }

        public virtual Physician Physician { get; set; }

        public Company()
        {
            Addresses = new System.Collections.Generic.List<Address>();
            AvailableDays = new System.Collections.Generic.List<AvailableDay>();
            Companies = new System.Collections.Generic.List<Company>();
            Services = new System.Collections.Generic.List<Service>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
