// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    public partial class CompanyService
    {
        public System.Guid Id { get; set; }
        public System.Guid? ServiceId { get; set; }
        public decimal? Price { get; set; }
        public System.Guid CompanyId { get; set; }
        public string Name { get; set; }
        public bool IsTravelRequired { get; set; }


        public virtual Service Service { get; set; }

        public CompanyService()
        {
            IsTravelRequired = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
