// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    // Company
    public partial class Company
    {
        public System.Guid Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 128)
        public string Description { get; set; } // Description
        public string Code { get; set; } // Code (length: 10)
        public string ColorCode { get; set; } // ColorCode (length: 10)
        public System.Guid? PhysicianId { get; set; } // PhysicianId
        public string BillingEmail { get; set; } // BillingEmail (length: 100)
        public string ReportsEmail { get; set; } // ReportsEmail (length: 100)
        public string PhoneNumber { get; set; } // PhoneNumber (length: 100)
        public System.Guid? ParentId { get; set; } // ParentId
        public int NoShowRate { get; set; } // NoShowRate
        public int LateCancellationRate { get; set; } // LateCancellationRate
        public int LateCancellationPolicy { get; set; } // LateCancellationPolicy
        public byte LateCancellationRateFormat { get; set; } // LateCancellationRateFormat
        public byte NoShowRateFormat { get; set; } // NoShowRateFormat

        // Reverse navigation

        /// <summary>
        /// Child Companies where [Company].[ParentId] point to this entity (FK_Company_ParentId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Company> Companies { get; set; } // Company.FK_Company_ParentId
        /// <summary>
        /// Child Services where [Service].[CompanyId] point to this entity (FK_Service_Company)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Service> Services { get; set; } // Service.FK_Service_Company

        // Foreign keys

        /// <summary>
        /// Parent Company pointed by [Company].([ParentId]) (FK_Company_ParentId)
        /// </summary>
        public virtual Company Parent { get; set; } // FK_Company_ParentId

        /// <summary>
        /// Parent Physician pointed by [Company].([PhysicianId]) (FK_Company_Physician)
        /// </summary>
        public virtual Physician Physician { get; set; } // FK_Company_Physician

        public Company()
        {
            Companies = new System.Collections.Generic.List<Company>();
            Services = new System.Collections.Generic.List<Service>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
