// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    public partial class Country
    {
        public short Id { get; set; }
        public string Name { get; set; }
        public short Iso3DigitCountry { get; set; }
        public string Iso2CountryCode { get; set; }
        public string Iso3CountryCode { get; set; }

        public virtual System.Collections.Generic.ICollection<Province> Provinces { get; set; }

        public Country()
        {
            Provinces = new System.Collections.Generic.List<Province>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
