

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Connection String:      "Data Source=(local);Initial Catalog=ImeHub;Integrated Security=True;Application Name=ImeHub"
// ------------------------------------------------------------------------------------------------
// Database Edition        : Developer Edition (64-bit)
// Database Engine Edition : Enterprise
// Database Version        : 14.0.1000.169

// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    #region POCO Configuration

    // Address
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class AddressConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Address>
    {
        public AddressConfiguration()
            : this("dbo")
        {
        }

        public AddressConfiguration(string schema)
        {
            ToTable("Address", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.PhysicianId).HasColumnName(@"PhysicianId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.CompanyId).HasColumnName(@"CompanyId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.AddressTypeId).HasColumnName(@"AddressTypeID").HasColumnType("tinyint").IsRequired();
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsOptional().HasMaxLength(256);
            Property(x => x.Attention).HasColumnName(@"Attention").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Address1).HasColumnName(@"Address1").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.Address2).HasColumnName(@"Address2").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.CityId).HasColumnName(@"CityId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.PostalCode).HasColumnName(@"PostalCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.TimeZoneId).HasColumnName(@"TimeZoneId").HasColumnType("smallint").IsRequired();

            // Foreign keys
            HasOptional(a => a.Physician).WithMany(b => b.Addresses).HasForeignKey(c => c.PhysicianId).WillCascadeOnDelete(false); // FK_Address_Physician
            HasRequired(a => a.AddressType).WithMany(b => b.Addresses).HasForeignKey(c => c.AddressTypeId).WillCascadeOnDelete(false); // FK_Address_AddressType
            HasRequired(a => a.City).WithMany(b => b.Addresses).HasForeignKey(c => c.CityId).WillCascadeOnDelete(false); // FK_Address_City
            HasRequired(a => a.TimeZone).WithMany(b => b.Addresses).HasForeignKey(c => c.TimeZoneId).WillCascadeOnDelete(false); // FK_Address_TimeZone
        }
    }

    // AddressType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class AddressTypeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AddressType>
    {
        public AddressTypeConfiguration()
            : this("dbo")
        {
        }

        public AddressTypeConfiguration(string schema)
        {
            ToTable("AddressType", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("tinyint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
        }
    }

    // City
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class CityConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<City>
    {
        public CityConfiguration()
            : this("dbo")
        {
        }

        public CityConfiguration(string schema)
        {
            ToTable("City", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("nvarchar").IsOptional().HasMaxLength(3);
            Property(x => x.ProvinceId).HasColumnName(@"ProvinceId").HasColumnType("smallint").IsRequired();

            // Foreign keys
            HasRequired(a => a.Province).WithMany(b => b.Cities).HasForeignKey(c => c.ProvinceId).WillCascadeOnDelete(false); // FK_City_Province
        }
    }

    // Company
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class CompanyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Company>
    {
        public CompanyConfiguration()
            : this("dbo")
        {
        }

        public CompanyConfiguration(string schema)
        {
            ToTable("Company", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.ColorCode).HasColumnName(@"ColorCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(10);
            Property(x => x.PhysicianId).HasColumnName(@"PhysicianId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.BillingEmail).HasColumnName(@"BillingEmail").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.ReportsEmail).HasColumnName(@"ReportsEmail").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.PhoneNumber).HasColumnName(@"PhoneNumber").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.ParentId).HasColumnName(@"ParentId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.NoShowRate).HasColumnName(@"NoShowRate").HasColumnType("int").IsRequired();
            Property(x => x.LateCancellationRate).HasColumnName(@"LateCancellationRate").HasColumnType("int").IsRequired();
            Property(x => x.LateCancellationPolicy).HasColumnName(@"LateCancellationPolicy").HasColumnType("int").IsRequired();
            Property(x => x.LateCancellationRateFormat).HasColumnName(@"LateCancellationRateFormat").HasColumnType("tinyint").IsRequired();
            Property(x => x.NoShowRateFormat).HasColumnName(@"NoShowRateFormat").HasColumnType("tinyint").IsRequired();

            // Foreign keys
            HasOptional(a => a.Parent).WithMany(b => b.Companies).HasForeignKey(c => c.ParentId).WillCascadeOnDelete(false); // FK_Company_ParentId
            HasOptional(a => a.Physician).WithMany(b => b.Companies).HasForeignKey(c => c.PhysicianId); // FK_Company_Physician
        }
    }

    // Country
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class CountryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Country>
    {
        public CountryConfiguration()
            : this("dbo")
        {
        }

        public CountryConfiguration(string schema)
        {
            ToTable("Country", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("smallint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.Iso3DigitCountry).HasColumnName(@"ISO3DigitCountry").HasColumnType("smallint").IsRequired();
            Property(x => x.Iso2CountryCode).HasColumnName(@"ISO2CountryCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(2);
            Property(x => x.Iso3CountryCode).HasColumnName(@"ISO3CountryCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(3);
        }
    }

    // Feature
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class FeatureConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Feature>
    {
        public FeatureConfiguration()
            : this("dbo")
        {
        }

        public FeatureConfiguration(string schema)
        {
            ToTable("Feature", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.ParentId).HasColumnName(@"ParentID").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasOptional(a => a.Parent).WithMany(b => b.Features).HasForeignKey(c => c.ParentId).WillCascadeOnDelete(false); // FK_Feature_Parent
        }
    }

    // Physician
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class PhysicianConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Physician>
    {
        public PhysicianConfiguration()
            : this("dbo")
        {
        }

        public PhysicianConfiguration(string schema)
        {
            ToTable("Physician", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CompanyName).HasColumnName(@"CompanyName").HasColumnType("nvarchar").IsOptional().HasMaxLength(250);
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.ColorCode).HasColumnName(@"ColorCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.OwnerId).HasColumnName(@"OwnerId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.ManagerId).HasColumnName(@"ManagerId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.PrimaryAddressId).HasColumnName(@"PrimaryAddressId").HasColumnType("smallint").IsOptional();
            Property(x => x.Designations).HasColumnName(@"Designations").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);

            // Foreign keys
            HasOptional(a => a.Owner).WithMany(b => b.Physicians_OwnerId).HasForeignKey(c => c.OwnerId).WillCascadeOnDelete(false); // FK_Physician_Owner
            HasRequired(a => a.Manager).WithMany(b => b.Physicians_ManagerId).HasForeignKey(c => c.ManagerId).WillCascadeOnDelete(false); // FK_Physician_Manager
        }
    }

    // PhysicianInviteLog
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class PhysicianInviteLogConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PhysicianInviteLog>
    {
        public PhysicianInviteLogConfiguration()
            : this("dbo")
        {
        }

        public PhysicianInviteLogConfiguration(string schema)
        {
            ToTable("PhysicianInviteLog", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.PhysicianId).HasColumnName(@"PhysicianId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.To).HasColumnName(@"To").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.Cc).HasColumnName(@"Cc").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.Bcc).HasColumnName(@"Bcc").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.Subject).HasColumnName(@"Subject").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.Body).HasColumnName(@"Body").HasColumnType("nvarchar(max)").IsRequired();

            // Foreign keys
            HasRequired(a => a.Physician).WithMany(b => b.PhysicianInviteLogs).HasForeignKey(c => c.PhysicianId).WillCascadeOnDelete(false); // FK_PhysicianInviteLog_Physician
        }
    }

    // PhysicianOwner
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class PhysicianOwnerConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PhysicianOwner>
    {
        public PhysicianOwnerConfiguration()
            : this("dbo")
        {
        }

        public PhysicianOwnerConfiguration(string schema)
        {
            ToTable("PhysicianOwner", schema);
            HasKey(x => x.PhysicianId);

            Property(x => x.PhysicianId).HasColumnName(@"PhysicianId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Email).HasColumnName(@"Email").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.AcceptanceStatusId).HasColumnName(@"AcceptanceStatusId").HasColumnType("tinyint").IsRequired();
            Property(x => x.AcceptanceStatusChangedDate).HasColumnName(@"AcceptanceStatusChangedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.FirstName).HasColumnName(@"FirstName").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.LastName).HasColumnName(@"LastName").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);

            // Foreign keys
            HasOptional(a => a.User).WithMany(b => b.PhysicianOwners).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // FK_PhysicianOwner_User
            HasRequired(a => a.Physician).WithOptional(b => b.PhysicianOwner).WillCascadeOnDelete(false); // FK_PhysicianOwner_Physician
            HasRequired(a => a.PhysicianOwnerAcceptanceStatu).WithMany(b => b.PhysicianOwners).HasForeignKey(c => c.AcceptanceStatusId).WillCascadeOnDelete(false); // FK_PhysicianOwner_PhysicianOwnerAcceptanceStatus
        }
    }

    // PhysicianOwnerAcceptanceStatus
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class PhysicianOwnerAcceptanceStatuConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PhysicianOwnerAcceptanceStatu>
    {
        public PhysicianOwnerAcceptanceStatuConfiguration()
            : this("dbo")
        {
        }

        public PhysicianOwnerAcceptanceStatuConfiguration(string schema)
        {
            ToTable("PhysicianOwnerAcceptanceStatus", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("tinyint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.ColorCode).HasColumnName(@"ColorCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
        }
    }

    // Province
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class ProvinceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Province>
    {
        public ProvinceConfiguration()
            : this("dbo")
        {
        }

        public ProvinceConfiguration(string schema)
        {
            ToTable("Province", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("smallint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CountryId).HasColumnName(@"CountryID").HasColumnType("smallint").IsRequired();
            Property(x => x.ProvinceName).HasColumnName(@"ProvinceName").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.ProvinceCode).HasColumnName(@"ProvinceCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.ProvinceTypeId).HasColumnName(@"ProvinceTypeID").HasColumnType("tinyint").IsOptional();

            // Foreign keys
            HasRequired(a => a.Country).WithMany(b => b.Provinces).HasForeignKey(c => c.CountryId).WillCascadeOnDelete(false); // FK_Province_Country
        }
    }

    // Role
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class RoleConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Role>
    {
        public RoleConfiguration()
            : this("dbo")
        {
        }

        public RoleConfiguration(string schema)
        {
            ToTable("Role", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(256);
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.ColorCode).HasColumnName(@"ColorCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
        }
    }

    // RoleFeature
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class RoleFeatureConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RoleFeature>
    {
        public RoleFeatureConfiguration()
            : this("dbo")
        {
        }

        public RoleFeatureConfiguration(string schema)
        {
            ToTable("RoleFeature", schema);
            HasKey(x => new { x.RoleId, x.FeatureId });

            Property(x => x.RoleId).HasColumnName(@"RoleId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.FeatureId).HasColumnName(@"FeatureId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.Feature).WithMany(b => b.RoleFeatures).HasForeignKey(c => c.FeatureId).WillCascadeOnDelete(false); // FK_RoleFeature_Feature
            HasRequired(a => a.Role).WithMany(b => b.RoleFeatures).HasForeignKey(c => c.RoleId).WillCascadeOnDelete(false); // FK_RoleFeature_Role
        }
    }

    // Service
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class ServiceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Service>
    {
        public ServiceConfiguration()
            : this("dbo")
        {
        }

        public ServiceConfiguration(string schema)
        {
            ToTable("Service", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CompanyId).HasColumnName(@"CompanyId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(2000);
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.ColorCode).HasColumnName(@"ColorCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(10);
            Property(x => x.Price).HasColumnName(@"Price").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.IsTravelRequired).HasColumnName(@"IsTravelRequired").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.Company).WithMany(b => b.Services).HasForeignKey(c => c.CompanyId); // FK_Service_Company
        }
    }

    // TeamMember
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class TeamMemberConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TeamMember>
    {
        public TeamMemberConfiguration()
            : this("dbo")
        {
        }

        public TeamMemberConfiguration(string schema)
        {
            ToTable("TeamMember", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.PhysicianId).HasColumnName(@"PhysicianId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.RoleId).HasColumnName(@"RoleId").HasColumnType("uniqueidentifier").IsRequired();

            // Foreign keys
            HasRequired(a => a.Physician).WithMany(b => b.TeamMembers).HasForeignKey(c => c.PhysicianId).WillCascadeOnDelete(false); // FK_TeamMember_Physician
            HasRequired(a => a.Role).WithMany(b => b.TeamMembers).HasForeignKey(c => c.RoleId).WillCascadeOnDelete(false); // FK_TeamMember_Role
            HasRequired(a => a.User).WithMany(b => b.TeamMembers).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // FK_TeamMember_User
        }
    }

    // TimeZone
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class TimeZoneConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TimeZone>
    {
        public TimeZoneConfiguration()
            : this("dbo")
        {
        }

        public TimeZoneConfiguration(string schema)
        {
            ToTable("TimeZone", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("smallint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.Iana).HasColumnName(@"IANA").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Iso).HasColumnName(@"ISO").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
        }
    }

    // TravelPrice
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class TravelPriceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TravelPrice>
    {
        public TravelPriceConfiguration()
            : this("dbo")
        {
        }

        public TravelPriceConfiguration(string schema)
        {
            ToTable("TravelPrice", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ServiceId).HasColumnName(@"ServiceId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.Price).HasColumnName(@"Price").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.CityId).HasColumnName(@"CityId").HasColumnType("uniqueidentifier").IsRequired();

            // Foreign keys
            HasRequired(a => a.City).WithMany(b => b.TravelPrices).HasForeignKey(c => c.CityId).WillCascadeOnDelete(false); // FK_TravelPrice_City
            HasRequired(a => a.Service).WithMany(b => b.TravelPrices).HasForeignKey(c => c.ServiceId); // FK_TravelPrice_Service
        }
    }

    // User
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class UserConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<User>
    {
        public UserConfiguration()
            : this("dbo")
        {
        }

        public UserConfiguration(string schema)
        {
            ToTable("User", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Email).HasColumnName(@"Email").HasColumnType("nvarchar").IsOptional().HasMaxLength(256);
            Property(x => x.EmailConfirmed).HasColumnName(@"EmailConfirmed").HasColumnType("bit").IsRequired();
            Property(x => x.PasswordHash).HasColumnName(@"PasswordHash").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.SecurityStamp).HasColumnName(@"SecurityStamp").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.PhoneNumber).HasColumnName(@"PhoneNumber").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.PhoneNumberConfirmed).HasColumnName(@"PhoneNumberConfirmed").HasColumnType("bit").IsRequired();
            Property(x => x.TwoFactorEnabled).HasColumnName(@"TwoFactorEnabled").HasColumnType("bit").IsRequired();
            Property(x => x.LockoutEndDateUtc).HasColumnName(@"LockoutEndDateUtc").HasColumnType("datetime").IsOptional();
            Property(x => x.LockoutEnabled).HasColumnName(@"LockoutEnabled").HasColumnType("bit").IsRequired();
            Property(x => x.AccessFailedCount).HasColumnName(@"AccessFailedCount").HasColumnType("int").IsRequired();
            Property(x => x.UserName).HasColumnName(@"UserName").HasColumnType("nvarchar").IsRequired().HasMaxLength(256);
            Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.FirstName).HasColumnName(@"FirstName").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.LastName).HasColumnName(@"LastName").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.LastActivationDate).HasColumnName(@"LastActivationDate").HasColumnType("datetime").IsOptional();
            Property(x => x.LogoCssClass).HasColumnName(@"LogoCssClass").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.ColorCode).HasColumnName(@"ColorCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Notes).HasColumnName(@"Notes").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.IsTestRecord).HasColumnName(@"IsTestRecord").HasColumnType("bit").IsRequired();
            Property(x => x.IsAppTester).HasColumnName(@"IsAppTester").HasColumnType("bit").IsRequired();
            Property(x => x.PhysicianId).HasColumnName(@"PhysicianId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.RoleId).HasColumnName(@"RoleId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.EmailProviderCredential).HasColumnName(@"EmailProviderCredential").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.EmailProvider).HasColumnName(@"EmailProvider").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);

            // Foreign keys
            HasRequired(a => a.Role).WithMany(b => b.Users).HasForeignKey(c => c.RoleId).WillCascadeOnDelete(false); // FK_User_Role
        }
    }

    // UserClaim
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class UserClaimConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UserClaim>
    {
        public UserClaimConfiguration()
            : this("dbo")
        {
        }

        public UserClaimConfiguration(string schema)
        {
            ToTable("UserClaim", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.ClaimType).HasColumnName(@"ClaimType").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.ClaimValue).HasColumnName(@"ClaimValue").HasColumnType("nvarchar(max)").IsOptional();

            // Foreign keys
            HasRequired(a => a.User).WithMany(b => b.UserClaims).HasForeignKey(c => c.UserId); // FK_UserClaim_User
        }
    }

    // UserLogin
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class UserLoginConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UserLogin>
    {
        public UserLoginConfiguration()
            : this("dbo")
        {
        }

        public UserLoginConfiguration(string schema)
        {
            ToTable("UserLogin", schema);
            HasKey(x => new { x.LoginProvider, x.ProviderKey, x.UserId });

            Property(x => x.LoginProvider).HasColumnName(@"LoginProvider").HasColumnType("nvarchar").IsRequired().HasMaxLength(128).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ProviderKey).HasColumnName(@"ProviderKey").HasColumnType("nvarchar").IsRequired().HasMaxLength(128).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.User).WithMany(b => b.UserLogins).HasForeignKey(c => c.UserId); // FK_UserLogin_User
        }
    }

    // UserRole
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class UserRoleConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UserRole>
    {
        public UserRoleConfiguration()
            : this("dbo")
        {
        }

        public UserRoleConfiguration(string schema)
        {
            ToTable("UserRole", schema);
            HasKey(x => new { x.UserId, x.RoleId });

            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.RoleId).HasColumnName(@"RoleId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.Role).WithMany(b => b.UserRoles).HasForeignKey(c => c.RoleId).WillCascadeOnDelete(false); // FK_UserRole_Role
            HasRequired(a => a.User).WithMany(b => b.UserRoles).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // FK_UserRole_User
        }
    }

    // UserSetupWorkflow
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class UserSetupWorkflowConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UserSetupWorkflow>
    {
        public UserSetupWorkflowConfiguration()
            : this("dbo")
        {
        }

        public UserSetupWorkflowConfiguration(string schema)
        {
            ToTable("UserSetupWorkflow", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.WorkflowId).HasColumnName(@"WorkflowId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.StatusId).HasColumnName(@"StatusId").HasColumnType("tinyint").IsRequired();
            Property(x => x.StatusChangedById).HasColumnName(@"StatusChangedById").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.StatusChangedDate).HasColumnName(@"StatusChangedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.User).WithOptional(b => b.UserSetupWorkflow); // FK_UserSetupWorkflow_User
            HasRequired(a => a.StatusChangedBy).WithMany(b => b.UserSetupWorkflows).HasForeignKey(c => c.StatusChangedById).WillCascadeOnDelete(false); // FK_UserSetupWorkflow_StatusChangedBy_User
        }
    }

    // UserSetupWorkItem
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class UserSetupWorkItemConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UserSetupWorkItem>
    {
        public UserSetupWorkItemConfiguration()
            : this("dbo")
        {
        }

        public UserSetupWorkItemConfiguration(string schema)
        {
            ToTable("UserSetupWorkItem", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CreatedFromWorkItemId).HasColumnName(@"CreatedFromWorkItemId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.Sequence).HasColumnName(@"Sequence").HasColumnType("smallint").IsRequired();
            Property(x => x.UserSetupWorkflowId).HasColumnName(@"UserSetupWorkflowId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.ResponsibleRoleId).HasColumnName(@"ResponsibleRoleId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.StatusId).HasColumnName(@"StatusId").HasColumnType("tinyint").IsRequired();
            Property(x => x.StatusChangedById).HasColumnName(@"StatusChangedById").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.StatusChangedDate).HasColumnName(@"StatusChangedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.AssignedToId).HasColumnName(@"AssignedToId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.AssignedToChangedById).HasColumnName(@"AssignedToChangedById").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.AssignedToChangedDate).HasColumnName(@"AssignedToChangedDate").HasColumnType("datetime").IsOptional();
            Property(x => x.DueDate).HasColumnName(@"DueDate").HasColumnType("datetime").IsOptional();

            // Foreign keys
            HasRequired(a => a.User).WithMany(b => b.UserSetupWorkItems).HasForeignKey(c => c.StatusChangedById).WillCascadeOnDelete(false); // FK_UserSetupWorkItem_StatusChangedBy_User
            HasRequired(a => a.UserSetupWorkflow).WithMany(b => b.UserSetupWorkItems).HasForeignKey(c => c.UserSetupWorkflowId); // FK_UserSetupWorkItem_UserSetupWorkflow
        }
    }

    // Workflow
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class WorkflowConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Workflow>
    {
        public WorkflowConfiguration()
            : this("dbo")
        {
        }

        public WorkflowConfiguration(string schema)
        {
            ToTable("Workflow", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.PhysicianId).HasColumnName(@"PhysicianId").HasColumnType("uniqueidentifier").IsOptional();
        }
    }

    // WorkItem
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class WorkItemConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WorkItem>
    {
        public WorkItemConfiguration()
            : this("dbo")
        {
        }

        public WorkItemConfiguration(string schema)
        {
            ToTable("WorkItem", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Sequence).HasColumnName(@"Sequence").HasColumnType("smallint").IsRequired();
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.RoleId).HasColumnName(@"RoleId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.IsBaselineDate).HasColumnName(@"IsBaselineDate").HasColumnType("bit").IsRequired();
            Property(x => x.DueDateDurationFromBaseline).HasColumnName(@"DueDateDurationFromBaseline").HasColumnType("smallint").IsOptional();
            Property(x => x.EffectiveDateDurationFromBaseline).HasColumnName(@"EffectiveDateDurationFromBaseline").HasColumnType("smallint").IsOptional();
            Property(x => x.IsCriticalPath).HasColumnName(@"IsCriticalPath").HasColumnType("bit").IsRequired();
            Property(x => x.IsBillable).HasColumnName(@"IsBillable").HasColumnType("bit").IsRequired();
            Property(x => x.WorkflowId).HasColumnName(@"WorkflowId").HasColumnType("uniqueidentifier").IsRequired();

            // Foreign keys
            HasRequired(a => a.Workflow).WithMany(b => b.WorkItems).HasForeignKey(c => c.WorkflowId); // FK_WorkItem_Workflow
        }
    }

    // WorkItemRelated
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class WorkItemRelatedConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WorkItemRelated>
    {
        public WorkItemRelatedConfiguration()
            : this("dbo")
        {
        }

        public WorkItemRelatedConfiguration(string schema)
        {
            ToTable("WorkItemRelated", schema);
            HasKey(x => new { x.ParentId, x.ChildId });

            Property(x => x.ParentId).HasColumnName(@"ParentId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ChildId).HasColumnName(@"ChildId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.Child).WithMany(b => b.WorkItemRelateds_ChildId).HasForeignKey(c => c.ChildId).WillCascadeOnDelete(false); // FK_WorkItemRelated_Dependent
            HasRequired(a => a.Parent).WithMany(b => b.WorkItemRelateds_ParentId).HasForeignKey(c => c.ParentId).WillCascadeOnDelete(false); // FK_WorkItemRelated_WorkItem
        }
    }

    #endregion

}
// </auto-generated>

