// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    public partial class Physician
    {
        public System.Guid Id { get; set; }
        public string CompanyName { get; set; }
        public string Code { get; set; }
        public string ColorCode { get; set; }
        public System.Guid? OwnerId { get; set; }
        public System.Guid ManagerId { get; set; }
        public short? PrimaryAddressId { get; set; }
        public string Designations { get; set; }

        public virtual PhysicianOwner PhysicianOwner { get; set; }
        public virtual System.Collections.Generic.ICollection<Address> Addresses { get; set; }
        public virtual System.Collections.Generic.ICollection<AvailableDay> AvailableDays { get; set; }
        public virtual System.Collections.Generic.ICollection<Case> Cases { get; set; }
        public virtual System.Collections.Generic.ICollection<City> Cities { get; set; }
        public virtual System.Collections.Generic.ICollection<Company> Companies { get; set; }
        public virtual System.Collections.Generic.ICollection<PhysicianInviteLog> PhysicianInviteLogs { get; set; }
        public virtual System.Collections.Generic.ICollection<ServiceRequest> ServiceRequests { get; set; }
        public virtual System.Collections.Generic.ICollection<TeamMember> TeamMembers { get; set; }
        public virtual System.Collections.Generic.ICollection<TeamMemberInvite> TeamMemberInvites { get; set; }
        public virtual System.Collections.Generic.ICollection<TeamRole> TeamRoles { get; set; }
        public virtual System.Collections.Generic.ICollection<Workflow> Workflows { get; set; }


        public virtual User Manager { get; set; }

        public virtual User Owner { get; set; }

        public Physician()
        {
            Addresses = new System.Collections.Generic.List<Address>();
            AvailableDays = new System.Collections.Generic.List<AvailableDay>();
            Cases = new System.Collections.Generic.List<Case>();
            Cities = new System.Collections.Generic.List<City>();
            Companies = new System.Collections.Generic.List<Company>();
            PhysicianInviteLogs = new System.Collections.Generic.List<PhysicianInviteLog>();
            ServiceRequests = new System.Collections.Generic.List<ServiceRequest>();
            TeamMembers = new System.Collections.Generic.List<TeamMember>();
            TeamMemberInvites = new System.Collections.Generic.List<TeamMemberInvite>();
            TeamRoles = new System.Collections.Generic.List<TeamRole>();
            Workflows = new System.Collections.Generic.List<Workflow>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
