// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    // PhysicianInvite
    public partial class PhysicianInvite
    {
        public System.Guid Id { get; set; } // Id (Primary key)
        public System.Guid PhysicianId { get; set; } // PhysicianId
        public string ToEmail { get; set; } // ToEmail (length: 128)
        public string ToName { get; set; } // ToName (length: 128)
        public System.Guid? UserId { get; set; } // UserId
        public System.DateTime? SentDate { get; set; } // SentDate
        public System.DateTime? LinkClickedDate { get; set; } // LinkClickedDate
        public string FromEmail { get; set; } // FromEmail (length: 128)
        public string FromName { get; set; } // FromName (length: 128)
        public byte AcceptanceStatusId { get; set; } // AcceptanceStatusId

        // Foreign keys

        /// <summary>
        /// Parent Physician pointed by [PhysicianInvite].([PhysicianId]) (FK_PhysicianInvite_Physician)
        /// </summary>
        public virtual Physician Physician { get; set; } // FK_PhysicianInvite_Physician

        /// <summary>
        /// Parent PhysicianInviteAcceptanceStatu pointed by [PhysicianInvite].([AcceptanceStatusId]) (FK_PhysicianInvite_PhysicianInviteAcceptanceStatus)
        /// </summary>
        public virtual PhysicianInviteAcceptanceStatu PhysicianInviteAcceptanceStatu { get; set; } // FK_PhysicianInvite_PhysicianInviteAcceptanceStatus

        /// <summary>
        /// Parent User pointed by [PhysicianInvite].([UserId]) (FK_PhysicianInvite_User)
        /// </summary>
        public virtual User User { get; set; } // FK_PhysicianInvite_User

        public PhysicianInvite()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
