// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    // PhysicianOwnerAcceptanceStatus
    public partial class PhysicianOwnerAcceptanceStatu
    {
        public byte Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public string Code { get; set; } // Code (length: 10)
        public string ColorCode { get; set; } // ColorCode (length: 10)

        // Reverse navigation

        /// <summary>
        /// Child PhysicianOwners where [PhysicianOwner].[AcceptanceStatusId] point to this entity (FK_PhysicianOwner_PhysicianOwnerAcceptanceStatus)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PhysicianOwner> PhysicianOwners { get; set; } // PhysicianOwner.FK_PhysicianOwner_PhysicianOwnerAcceptanceStatus

        public PhysicianOwnerAcceptanceStatu()
        {
            PhysicianOwners = new System.Collections.Generic.List<PhysicianOwner>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
