// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    // Province
    public partial class Province
    {
        public short Id { get; set; } // Id (Primary key)
        public short CountryId { get; set; } // CountryID
        public string ProvinceName { get; set; } // ProvinceName (length: 100)
        public string ProvinceCode { get; set; } // ProvinceCode (length: 50)
        public byte? ProvinceTypeId { get; set; } // ProvinceTypeID

        // Reverse navigation

        /// <summary>
        /// Child Cities where [City].[ProvinceId] point to this entity (FK_City_Province)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<City> Cities { get; set; } // City.FK_City_Province

        // Foreign keys

        /// <summary>
        /// Parent Country pointed by [Province].([CountryId]) (FK_Province_Country)
        /// </summary>
        public virtual Country Country { get; set; } // FK_Province_Country

        public Province()
        {
            Cities = new System.Collections.Generic.List<City>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
