// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    public partial class Province
    {
        public short Id { get; set; }
        public short CountryId { get; set; }
        public string ProvinceName { get; set; }
        public string ProvinceCode { get; set; }
        public byte? ProvinceTypeId { get; set; }

        public virtual System.Collections.Generic.ICollection<City> Cities { get; set; }


        public virtual Country Country { get; set; }

        public Province()
        {
            Cities = new System.Collections.Generic.List<City>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
