// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    public partial class Role
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ColorCode { get; set; }

        public virtual System.Collections.Generic.ICollection<RoleFeature> RoleFeatures { get; set; }
        public virtual System.Collections.Generic.ICollection<TeamMemberInvite> TeamMemberInvites { get; set; }
        public virtual System.Collections.Generic.ICollection<User> Users { get; set; }
        public virtual System.Collections.Generic.ICollection<UserRole> UserRoles { get; set; }

        public Role()
        {
            RoleFeatures = new System.Collections.Generic.List<RoleFeature>();
            TeamMemberInvites = new System.Collections.Generic.List<TeamMemberInvite>();
            Users = new System.Collections.Generic.List<User>();
            UserRoles = new System.Collections.Generic.List<UserRole>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
