// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    // RoleFeature
    public partial class RoleFeature
    {
        public System.Guid Id { get; set; } // Id (Primary key)
        public System.Guid RoleId { get; set; } // RoleId
        public System.Guid FeatureId { get; set; } // FeatureId
        public bool IsActive { get; set; } // IsActive

        // Foreign keys

        /// <summary>
        /// Parent Feature pointed by [RoleFeature].([FeatureId]) (FK_RoleFeature_Feature)
        /// </summary>
        public virtual Feature Feature { get; set; } // FK_RoleFeature_Feature

        /// <summary>
        /// Parent Role pointed by [RoleFeature].([RoleId]) (FK_RoleFeature_Role)
        /// </summary>
        public virtual Role Role { get; set; } // FK_RoleFeature_Role

        public RoleFeature()
        {
            IsActive = true;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
