// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    public partial class RoleFeature
    {
        public System.Guid RoleId { get; set; }
        public System.Guid FeatureId { get; set; }


        public virtual Feature Feature { get; set; }

        public virtual Role Role { get; set; }

        public RoleFeature()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
