// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    // Service
    public partial class Service
    {
        public System.Guid Id { get; set; } // Id (Primary key)
        public System.Guid CompanyId { get; set; } // CompanyId
        public string Name { get; set; } // Name (length: 128)
        public string Description { get; set; } // Description (length: 2000)
        public string Code { get; set; } // Code (length: 10)
        public string ColorCode { get; set; } // ColorCode (length: 10)
        public decimal Price { get; set; } // Price
        public bool IsTravelRequired { get; set; } // IsTravelRequired

        // Reverse navigation

        /// <summary>
        /// Child TravelPrices where [TravelPrice].[ServiceId] point to this entity (FK_TravelPrice_Service)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TravelPrice> TravelPrices { get; set; } // TravelPrice.FK_TravelPrice_Service

        // Foreign keys

        /// <summary>
        /// Parent Company pointed by [Service].([CompanyId]) (FK_Service_Company)
        /// </summary>
        public virtual Company Company { get; set; } // FK_Service_Company

        public Service()
        {
            IsTravelRequired = false;
            TravelPrices = new System.Collections.Generic.List<TravelPrice>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
