// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    public partial class Service
    {
        public System.Guid Id { get; set; }
        public System.Guid CompanyId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public string ColorCode { get; set; }
        public decimal Price { get; set; }
        public bool IsTravelRequired { get; set; }

        public virtual System.Collections.Generic.ICollection<CompanyService> CompanyServices { get; set; }
        public virtual System.Collections.Generic.ICollection<ServiceRequest> ServiceRequests { get; set; }
        public virtual System.Collections.Generic.ICollection<TravelPrice> TravelPrices { get; set; }


        public virtual Company Company { get; set; }

        public Service()
        {
            IsTravelRequired = false;
            CompanyServices = new System.Collections.Generic.List<CompanyService>();
            ServiceRequests = new System.Collections.Generic.List<ServiceRequest>();
            TravelPrices = new System.Collections.Generic.List<TravelPrice>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
