// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    public partial class TeamMemberInvite
    {
        public System.Guid Id { get; set; }
        public string To { get; set; }
        public string Cc { get; set; }
        public string Bcc { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public byte InviteStatusId { get; set; }
        public System.DateTime InviteStatusChangedDate { get; set; }
        public System.Guid InviteStatusChangedBy { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.Guid RoleId { get; set; }
        public System.Guid PhysicianId { get; set; }

        public virtual System.Collections.Generic.ICollection<TeamMember> TeamMembers { get; set; }


        public virtual InviteStatu InviteStatu { get; set; }

        public virtual Physician Physician { get; set; }

        public virtual Role Role { get; set; }

        public TeamMemberInvite()
        {
            InviteStatusId = 4;
            TeamMembers = new System.Collections.Generic.List<TeamMember>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
