// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    // TeamMember
    public partial class TeamMember
    {
        public System.Guid Id { get; set; } // Id (Primary key)
        public System.Guid PhysicianId { get; set; } // PhysicianId
        public System.Guid UserId { get; set; } // UserId
        public System.Guid RoleId { get; set; } // RoleId

        // Foreign keys

        /// <summary>
        /// Parent Physician pointed by [TeamMember].([PhysicianId]) (FK_TeamMember_Physician)
        /// </summary>
        public virtual Physician Physician { get; set; } // FK_TeamMember_Physician

        /// <summary>
        /// Parent Role pointed by [TeamMember].([RoleId]) (FK_TeamMember_Role)
        /// </summary>
        public virtual Role Role { get; set; } // FK_TeamMember_Role

        /// <summary>
        /// Parent User pointed by [TeamMember].([UserId]) (FK_TeamMember_User)
        /// </summary>
        public virtual User User { get; set; } // FK_TeamMember_User

        public TeamMember()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
