// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    public partial class TeamRole
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ColorCode { get; set; }
        public System.Guid PhysicianId { get; set; }

        public virtual System.Collections.Generic.ICollection<TeamMember> TeamMembers { get; set; }
        public virtual System.Collections.Generic.ICollection<WorkItem> WorkItems { get; set; }


        public virtual Physician Physician { get; set; }

        public TeamRole()
        {
            TeamMembers = new System.Collections.Generic.List<TeamMember>();
            WorkItems = new System.Collections.Generic.List<WorkItem>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
