// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    public partial class TimeZone
    {
        public short Id { get; set; }
        public string Name { get; set; }
        public string Iana { get; set; }
        public string Iso { get; set; }

        public virtual System.Collections.Generic.ICollection<Address> Addresses { get; set; }

        public TimeZone()
        {
            Addresses = new System.Collections.Generic.List<Address>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
