// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    // TravelPrice
    public partial class TravelPrice
    {
        public System.Guid Id { get; set; } // Id (Primary key)
        public System.Guid ServiceId { get; set; } // ServiceId
        public decimal Price { get; set; } // Price
        public System.Guid CityId { get; set; } // CityId

        // Foreign keys

        /// <summary>
        /// Parent City pointed by [TravelPrice].([CityId]) (FK_TravelPrice_City)
        /// </summary>
        public virtual City City { get; set; } // FK_TravelPrice_City

        /// <summary>
        /// Parent Service pointed by [TravelPrice].([ServiceId]) (FK_TravelPrice_Service)
        /// </summary>
        public virtual Service Service { get; set; } // FK_TravelPrice_Service

        public TravelPrice()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
