// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    public partial class User
    {
        public System.Guid Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public System.DateTime? LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime? LastActivationDate { get; set; }
        public string LogoCssClass { get; set; }
        public string ColorCode { get; set; }
        public string Notes { get; set; }
        public bool IsTestRecord { get; set; }
        public bool IsAppTester { get; set; }
        public System.Guid? PhysicianId { get; set; }
        public System.Guid RoleId { get; set; }
        public string EmailProviderCredential { get; set; }
        public string EmailProvider { get; set; }

        public virtual System.Collections.Generic.ICollection<AvailableDayResource> AvailableDayResources { get; set; }
        public virtual System.Collections.Generic.ICollection<Physician> Physicians_ManagerId { get; set; }
        public virtual System.Collections.Generic.ICollection<Physician> Physicians_OwnerId { get; set; }
        public virtual System.Collections.Generic.ICollection<PhysicianOwner> PhysicianOwners { get; set; }
        public virtual System.Collections.Generic.ICollection<TeamMember> TeamMembers { get; set; }
        public virtual System.Collections.Generic.ICollection<UserClaim> UserClaims { get; set; }
        public virtual System.Collections.Generic.ICollection<UserLogin> UserLogins { get; set; }
        public virtual System.Collections.Generic.ICollection<UserRole> UserRoles { get; set; }
        public virtual System.Collections.Generic.ICollection<UserSetupWorkflow> UserSetupWorkflows { get; set; }
        public virtual System.Collections.Generic.ICollection<UserSetupWorkItem> UserSetupWorkItems { get; set; }
        public virtual UserSetupWorkflow UserSetupWorkflow { get; set; }


        public virtual Role Role { get; set; }

        public User()
        {
            IsTestRecord = false;
            IsAppTester = false;
            AvailableDayResources = new System.Collections.Generic.List<AvailableDayResource>();
            Physicians_ManagerId = new System.Collections.Generic.List<Physician>();
            Physicians_OwnerId = new System.Collections.Generic.List<Physician>();
            PhysicianOwners = new System.Collections.Generic.List<PhysicianOwner>();
            TeamMembers = new System.Collections.Generic.List<TeamMember>();
            UserClaims = new System.Collections.Generic.List<UserClaim>();
            UserLogins = new System.Collections.Generic.List<UserLogin>();
            UserRoles = new System.Collections.Generic.List<UserRole>();
            UserSetupWorkflows = new System.Collections.Generic.List<UserSetupWorkflow>();
            UserSetupWorkItems = new System.Collections.Generic.List<UserSetupWorkItem>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
