// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    public partial class UserSetupWorkflow
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid? WorkflowId { get; set; }
        public byte StatusId { get; set; }
        public System.Guid StatusChangedById { get; set; }
        public System.DateTime StatusChangedDate { get; set; }

        public virtual System.Collections.Generic.ICollection<UserSetupWorkItem> UserSetupWorkItems { get; set; }


        public virtual User User { get; set; }

        public virtual User StatusChangedBy { get; set; }

        public UserSetupWorkflow()
        {
            UserSetupWorkItems = new System.Collections.Generic.List<UserSetupWorkItem>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
