// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    // UserLogin
    public partial class UserLogin
    {
        public string LoginProvider { get; set; } // LoginProvider (Primary key) (length: 128)
        public string ProviderKey { get; set; } // ProviderKey (Primary key) (length: 128)
        public System.Guid UserId { get; set; } // UserId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [UserLogin].([UserId]) (FK_UserLogin_User)
        /// </summary>
        public virtual User User { get; set; } // FK_UserLogin_User

        public UserLogin()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
