// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    // WorkItem
    public partial class WorkItem
    {
        public System.Guid Id { get; set; } // Id (Primary key)
        public short Sequence { get; set; } // Sequence
        public string Name { get; set; } // Name (length: 128)
        public System.Guid? RoleId { get; set; } // RoleId
        public bool IsBaselineDate { get; set; } // IsBaselineDate
        public short? DueDateDurationFromBaseline { get; set; } // DueDateDurationFromBaseline
        public short? EffectiveDateDurationFromBaseline { get; set; } // EffectiveDateDurationFromBaseline
        public bool IsCriticalPath { get; set; } // IsCriticalPath
        public bool IsBillable { get; set; } // IsBillable
        public System.Guid WorkflowId { get; set; } // WorkflowId

        // Reverse navigation

        /// <summary>
        /// Child WorkItemRelateds where [WorkItemRelated].[ChildId] point to this entity (FK_WorkItemRelated_Dependent)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<WorkItemRelated> WorkItemRelateds_ChildId { get; set; } // WorkItemRelated.FK_WorkItemRelated_Dependent
        /// <summary>
        /// Child WorkItemRelateds where [WorkItemRelated].[ParentId] point to this entity (FK_WorkItemRelated_WorkItem)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<WorkItemRelated> WorkItemRelateds_ParentId { get; set; } // WorkItemRelated.FK_WorkItemRelated_WorkItem

        // Foreign keys

        /// <summary>
        /// Parent Workflow pointed by [WorkItem].([WorkflowId]) (FK_WorkItem_Workflow)
        /// </summary>
        public virtual Workflow Workflow { get; set; } // FK_WorkItem_Workflow

        public WorkItem()
        {
            IsBaselineDate = false;
            IsCriticalPath = false;
            IsBillable = false;
            WorkItemRelateds_ChildId = new System.Collections.Generic.List<WorkItemRelated>();
            WorkItemRelateds_ParentId = new System.Collections.Generic.List<WorkItemRelated>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
