// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    // WorkflowTask
    public partial class WorkflowTask
    {
        public System.Guid Id { get; set; } // Id (Primary key)
        public short WorkflowId { get; set; } // WorkflowId
        public short Sequence { get; set; } // Sequence
        public string Name { get; set; } // Name (length: 128)
        public System.Guid? RoleId { get; set; } // RoleId
        public bool IsBaselineDate { get; set; } // IsBaselineDate
        public short? DueDateDurationFromBaseline { get; set; } // DueDateDurationFromBaseline
        public short? EffectiveDateDurationFromBaseline { get; set; } // EffectiveDateDurationFromBaseline
        public bool IsCriticalPath { get; set; } // IsCriticalPath
        public bool IsBillable { get; set; } // IsBillable

        // Reverse navigation

        /// <summary>
        /// Child WorkflowTaskDependents where [WorkflowTaskDependent].[ChildId] point to this entity (FK_WorkflowTaskDependent_Dependent)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<WorkflowTaskDependent> WorkflowTaskDependents_ChildId { get; set; } // WorkflowTaskDependent.FK_WorkflowTaskDependent_Dependent
        /// <summary>
        /// Child WorkflowTaskDependents where [WorkflowTaskDependent].[ParentId] point to this entity (FK_WorkflowTaskDependent_WorkflowTask)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<WorkflowTaskDependent> WorkflowTaskDependents_ParentId { get; set; } // WorkflowTaskDependent.FK_WorkflowTaskDependent_WorkflowTask

        public WorkflowTask()
        {
            IsBaselineDate = false;
            IsCriticalPath = false;
            IsBillable = false;
            WorkflowTaskDependents_ChildId = new System.Collections.Generic.List<WorkflowTaskDependent>();
            WorkflowTaskDependents_ParentId = new System.Collections.Generic.List<WorkflowTaskDependent>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
