// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    // WorkflowTask
    public partial class WorkflowTask
    {
        public System.Guid Id { get; set; } // Id (Primary key)
        public short WorkflowId { get; set; } // WorkflowId
        public short Sequence { get; set; } // Sequence
        public string Name { get; set; } // Name (length: 128)
        public System.Guid? RoleId { get; set; } // RoleId
        public bool IsBaselineDate { get; set; } // IsBaselineDate
        public short? DueDateDurationFromBaseline { get; set; } // DueDateDurationFromBaseline
        public short? EffectiveDateDurationFromBaseline { get; set; } // EffectiveDateDurationFromBaseline
        public bool IsCriticalPath { get; set; } // IsCriticalPath
        public bool IsBillable { get; set; } // IsBillable

        // Reverse navigation

        /// <summary>
        /// Child WorkflowTasks (Many-to-Many) mapped by table [WorkflowTaskDependent]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<WorkflowTask> WorkflowTasks_ChildId { get; set; } // Many to many mapping
        /// <summary>
        /// Child WorkflowTasks (Many-to-Many) mapped by table [WorkflowTaskDependent]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<WorkflowTask> WorkflowTasks_ParentId { get; set; } // Many to many mapping

        public WorkflowTask()
        {
            IsBaselineDate = false;
            IsCriticalPath = false;
            IsBillable = false;
            WorkflowTasks_ChildId = new System.Collections.Generic.List<WorkflowTask>();
            WorkflowTasks_ParentId = new System.Collections.Generic.List<WorkflowTask>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
