// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ImeHub.Data
{

    public partial class WorkItem
    {
        public System.Guid Id { get; set; }
        public short Sequence { get; set; }
        public string Name { get; set; }
        public bool IsBaselineDate { get; set; }
        public short? DueDateDurationFromBaseline { get; set; }
        public short? EffectiveDateDurationFromBaseline { get; set; }
        public bool IsCriticalPath { get; set; }
        public bool IsBillable { get; set; }
        public System.Guid WorkflowId { get; set; }
        public System.Guid TeamRoleId { get; set; }

        public virtual System.Collections.Generic.ICollection<WorkItemRelated> WorkItemRelateds_ChildId { get; set; }
        public virtual System.Collections.Generic.ICollection<WorkItemRelated> WorkItemRelateds_ParentId { get; set; }


        public virtual TeamRole TeamRole { get; set; }

        public virtual Workflow Workflow { get; set; }

        public WorkItem()
        {
            IsBaselineDate = false;
            IsCriticalPath = false;
            IsBillable = false;
            WorkItemRelateds_ChildId = new System.Collections.Generic.List<WorkItemRelated>();
            WorkItemRelateds_ParentId = new System.Collections.Generic.List<WorkItemRelated>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
