// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WebApp.Areas.Reports.Data
{

    // InvoiceToQBExport
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class InvoiceToQbExport
    {
        public string InvoiceNumber { get; set; } // InvoiceNumber (Primary key) (length: 128)
        public System.DateTime InvoiceDate { get; set; } // InvoiceDate (Primary key)
        public System.DateTime? DueDate { get; set; } // DueDate
        public string ServiceProviderName { get; set; } // ServiceProviderName (Primary key) (length: 128)
        public string CustomerName { get; set; } // CustomerName (Primary key) (length: 128)
        public string CustomerProvince { get; set; } // CustomerProvince (length: 128)
        public decimal? SubTotal { get; set; } // SubTotal
        public decimal? TaxRateHst { get; set; } // TaxRateHst
        public decimal? Hst { get; set; } // Hst
        public decimal? Total { get; set; } // Total
        public string BillingEmail { get; set; } // BillingEmail (Primary key) (length: 128)
        public string ItemDescription { get; set; } // ItemDescription (length: 256)
        public bool IsDeleted { get; set; } // IsDeleted (Primary key)
        public System.DateTime? SentDate { get; set; } // SentDate
    }

}
// </auto-generated>
