// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WebApp.Areas.Reports.Data
{

    // InvoiceToQBExport
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class InvoiceToQbExportConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<InvoiceToQbExport>
    {
        public InvoiceToQbExportConfiguration()
            : this("API")
        {
        }

        public InvoiceToQbExportConfiguration(string schema)
        {
            ToTable("InvoiceToQBExport", schema);
            HasKey(x => new { x.InvoiceNumber, x.InvoiceDate, x.ServiceProviderName, x.CustomerName, x.BillingEmail, x.IsDeleted });

            Property(x => x.InvoiceNumber).HasColumnName(@"InvoiceNumber").HasColumnType("nvarchar").IsRequired().HasMaxLength(128).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.InvoiceDate).HasColumnName(@"InvoiceDate").HasColumnType("datetime").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.DueDate).HasColumnName(@"DueDate").HasColumnType("datetime").IsOptional();
            Property(x => x.ServiceProviderName).HasColumnName(@"ServiceProviderName").HasColumnType("nvarchar").IsRequired().HasMaxLength(128).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CustomerName).HasColumnName(@"CustomerName").HasColumnType("nvarchar").IsRequired().HasMaxLength(128).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CustomerProvince).HasColumnName(@"CustomerProvince").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.SubTotal).HasColumnName(@"SubTotal").HasColumnType("decimal").IsOptional().HasPrecision(10,2);
            Property(x => x.TaxRateHst).HasColumnName(@"TaxRateHst").HasColumnType("decimal").IsOptional().HasPrecision(10,2);
            Property(x => x.Hst).HasColumnName(@"Hst").HasColumnType("decimal").IsOptional().HasPrecision(10,2);
            Property(x => x.Total).HasColumnName(@"Total").HasColumnType("decimal").IsOptional().HasPrecision(10,2);
            Property(x => x.BillingEmail).HasColumnName(@"BillingEmail").HasColumnType("nvarchar").IsRequired().HasMaxLength(128).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ItemDescription).HasColumnName(@"ItemDescription").HasColumnType("nvarchar").IsOptional().HasMaxLength(256);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsOptional();
            Property(x => x.SentDate).HasColumnName(@"SentDate").HasColumnType("datetime").IsOptional();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.DeletedDate).HasColumnName(@"DeletedDate").HasColumnType("datetime").IsOptional();
            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsOptional();
            Property(x => x.ClaimantName).HasColumnName(@"ClaimantName").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.Service).HasColumnName(@"Service").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.City).HasColumnName(@"City").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.Province).HasColumnName(@"Province").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.IsNoShow).HasColumnName(@"IsNoShow").HasColumnType("bit").IsOptional();
            Property(x => x.IsLateCancellation).HasColumnName(@"IsLateCancellation").HasColumnType("bit").IsOptional();
            Property(x => x.Intake).HasColumnName(@"Intake").HasColumnType("nvarchar").IsOptional().HasMaxLength(257);
            Property(x => x.DocReviewer).HasColumnName(@"DocReviewer").HasColumnType("nvarchar").IsOptional().HasMaxLength(257);
        }
    }

}
// </auto-generated>
