// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WebApp.Areas.Reports.Data
{

    public class ReportsContextFactory : System.Data.Entity.Infrastructure.IDbContextFactory<ReportsContext>
    {
        public ReportsContext Create()
        {
            return new ReportsContext();
        }
    }
}
// </auto-generated>
