CREATE TABLE [dbo].[ServiceRequest] (
    [SysStartTime]                  DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
    [SysEndTime]                    DATETIME2 (7) GENERATED ALWAYS AS ROW END   NOT NULL,
    [Id]                            UNIQUEIDENTIFIER                            NOT NULL,
    [PhysicianId]                   UNIQUEIDENTIFIER                            NOT NULL,
    [CaseNumber]                    NVARCHAR (50)                               NOT NULL,
    [AlternateKey]                  NVARCHAR (128)                              NULL,
    [ClaimantName]                  NVARCHAR (128)                              NULL,
    [Title]                         NVARCHAR (256)                              NULL,
    [RequestedDate]                 DATETIME                                    NULL,
    [RequestedBy]                   UNIQUEIDENTIFIER                            NULL,
    [StatusId]                      TINYINT                                     NOT NULL,
    [StatusChangedById]             UNIQUEIDENTIFIER                            NULL,
    [StatusChangedDate]             DATETIME                                    NULL,
    [ServiceId]                     UNIQUEIDENTIFIER                            NOT NULL,
    [FolderUrl]                     NVARCHAR (256)                              NULL,
    [DueDate]                       DATE                                        NULL,
    [AvailableSlotId]               UNIQUEIDENTIFIER                            NULL,
    [AppointmentDate]               DATE                                        NULL,
    [StartTime]                     TIME (7)                                    NULL,
    [EndTime]                       TIME (7)                                    NULL,
    [AddressId]                     UNIQUEIDENTIFIER                            NULL,
    [CancellationStatusId]          TINYINT                                     NOT NULL,
    [CancellationStatusChangedDate] DATETIME                                    NULL,
    [CancellationStatusChangedById] UNIQUEIDENTIFIER                            NULL,
    [HasErrors]                     BIT                                         CONSTRAINT [DF_ServiceRequest_HasErrors] DEFAULT ((0)) NOT NULL,
    [HasWarnings]                   BIT                                         CONSTRAINT [DF_ServiceRequest_HasWarnings] DEFAULT ((0)) NOT NULL,
    [MedicolegalTypeId]             TINYINT                                     NULL,
    [ReferralSource]                NVARCHAR (200)                              NULL,
    CONSTRAINT [PK_ServiceRequest] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ServiceRequest_Address] FOREIGN KEY ([AddressId]) REFERENCES [dbo].[Address] ([Id]),
    CONSTRAINT [FK_ServiceRequest_AvailableSlot] FOREIGN KEY ([AvailableSlotId]) REFERENCES [dbo].[AvailableSlot] ([Id]),
    CONSTRAINT [FK_ServiceRequest_CancellationStatus] FOREIGN KEY ([CancellationStatusId]) REFERENCES [dbo].[CancellationStatus] ([Id]),
    CONSTRAINT [FK_ServiceRequest_MedicolegalType] FOREIGN KEY ([MedicolegalTypeId]) REFERENCES [dbo].[MedicolegalType] ([Id]),
    CONSTRAINT [FK_ServiceRequest_Physician] FOREIGN KEY ([PhysicianId]) REFERENCES [dbo].[Physician] ([Id]),
    CONSTRAINT [FK_ServiceRequest_Service] FOREIGN KEY ([ServiceId]) REFERENCES [dbo].[Service] ([Id]),
    CONSTRAINT [FK_ServiceRequest_ServiceRequestStatus] FOREIGN KEY ([StatusId]) REFERENCES [dbo].[ServiceRequestStatus] ([Id]),
    PERIOD FOR SYSTEM_TIME ([SysStartTime], [SysEndTime])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[dbo].[ServiceRequestHistory], DATA_CONSISTENCY_CHECK=ON));

