CREATE TABLE [dbo].[Time] (
    [Id]                         BIGINT         NOT NULL,
    [PK_Date]                    DATETIME       NOT NULL,
    [Date_Name]                  NVARCHAR (50)  NULL,
    [Year]                       DATETIME       NULL,
    [Year_Name]                  NVARCHAR (50)  NULL,
    [Half_Year]                  DATETIME       NULL,
    [Half_Year_Name]             NVARCHAR (50)  NULL,
    [Quarter]                    DATETIME       NULL,
    [Quarter_Name]               NVARCHAR (50)  NULL,
    [Month]                      DATETIME       NULL,
    [Month_Name]                 NVARCHAR (50)  NULL,
    [Ten_Days]                   DATETIME       NULL,
    [Ten_Days_Name]              NVARCHAR (50)  NULL,
    [Week]                       DATETIME       NULL,
    [Week_Name]                  NVARCHAR (50)  NULL,
    [Day_Of_Year]                INT            NULL,
    [Day_Of_Year_Name]           NVARCHAR (50)  NULL,
    [Day_Of_Half_Year]           INT            NULL,
    [Day_Of_Half_Year_Name]      NVARCHAR (50)  NULL,
    [Day_Of_Quarter]             INT            NULL,
    [Day_Of_Quarter_Name]        NVARCHAR (50)  NULL,
    [Day_Of_Month]               INT            NULL,
    [Day_Of_Month_Name]          NVARCHAR (50)  NULL,
    [Day_Of_Ten_Days]            INT            NULL,
    [Day_Of_Ten_Days_Name]       NVARCHAR (50)  NULL,
    [Day_Of_Week]                INT            NULL,
    [Day_Of_Week_Name]           NVARCHAR (50)  NULL,
    [Week_Of_Year]               INT            NULL,
    [Week_Of_Year_Name]          NVARCHAR (50)  NULL,
    [Ten_Days_Of_Year]           INT            NULL,
    [Ten_Days_Of_Year_Name]      NVARCHAR (50)  NULL,
    [Ten_Days_Of_Half_Year]      INT            NULL,
    [Ten_Days_Of_Half_Year_Name] NVARCHAR (50)  NULL,
    [Ten_Days_Of_Quarter]        INT            NULL,
    [Ten_Days_Of_Quarter_Name]   NVARCHAR (50)  NULL,
    [Ten_Days_Of_Month]          INT            NULL,
    [Ten_Days_Of_Month_Name]     NVARCHAR (50)  NULL,
    [Month_Of_Year]              INT            NULL,
    [Month_Of_Year_Name]         NVARCHAR (50)  NULL,
    [Month_Of_Half_Year]         INT            NULL,
    [Month_Of_Half_Year_Name]    NVARCHAR (50)  NULL,
    [Month_Of_Quarter]           INT            NULL,
    [Month_Of_Quarter_Name]      NVARCHAR (50)  NULL,
    [Quarter_Of_Year]            INT            NULL,
    [Quarter_Of_Year_Name]       NVARCHAR (50)  NULL,
    [Quarter_Of_Half_Year]       INT            NULL,
    [Quarter_Of_Half_Year_Name]  NVARCHAR (50)  NULL,
    [Half_Year_Of_Year]          INT            NULL,
    [Half_Year_Of_Year_Name]     NVARCHAR (50)  NULL,
    [ISO_8601_Year]              DATETIME       NULL,
    [ISO_8601_Year_Name]         NVARCHAR (50)  NULL,
    [ISO_8601_Week]              DATETIME       NULL,
    [ISO_8601_Week_Name]         NVARCHAR (50)  NULL,
    [ISO_8601_Day]               DATETIME       NULL,
    [ISO_8601_Day_Name]          NVARCHAR (50)  NULL,
    [ISO_8601_Day_Of_Year]       INT            NULL,
    [ISO_8601_Day_Of_Year_Name]  NVARCHAR (50)  NULL,
    [ISO_8601_Day_Of_Week]       INT            NULL,
    [ISO_8601_Day_Of_Week_Name]  NVARCHAR (50)  NULL,
    [ISO_8601_Week_Of_Year]      INT            NULL,
    [ISO_8601_Week_Of_Year_Name] NVARCHAR (50)  NULL,
    [Sortable_Year]              INT            NULL,
    [Sortable_Month]             NVARCHAR (133) NULL,
    [ModifiedDate]               DATETIME       NOT NULL,
    [ModifiedUser]               NVARCHAR (256) NULL
);








GO


